package com.javahacks.odx.lsp.dtos;

/**
 * {@link DiagnosticElement} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractDiagnosticElementAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class DiagnosticElementAssert extends AbstractDiagnosticElementAssert<DiagnosticElementAssert, DiagnosticElement> {

  /**
   * Creates a new <code>{@link DiagnosticElementAssert}</code> to make assertions on actual DiagnosticElement.
   * @param actual the DiagnosticElement we want to make assertions on.
   */
  public DiagnosticElementAssert(DiagnosticElement actual) {
    super(actual, DiagnosticElementAssert.class);
  }

  /**
   * An entry point for DiagnosticElementAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myDiagnosticElement)</code> and get specific assertion with code completion.
   * @param actual the DiagnosticElement we want to make assertions on.
   * @return a new <code>{@link DiagnosticElementAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static DiagnosticElementAssert assertThat(DiagnosticElement actual) {
    return new DiagnosticElementAssert(actual);
  }
}
