//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.28 at 09:58:19 AM CET 
//


package com.javahacks.odx.model;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * &lt;p&gt;Java class for ADDRDEF-PHYS-SEGMENT complex type.
 * <p>
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * <p>
 * &lt;pre&gt;
 * &amp;lt;complexType name="ADDRDEF-PHYS-SEGMENT"&amp;gt;
 * &amp;lt;complexContent&amp;gt;
 * &amp;lt;extension base="{}PHYS-SEGMENT"&amp;gt;
 * &amp;lt;sequence&amp;gt;
 * &amp;lt;element name="END-ADDRESS" type="{http://www.w3.org/2001/XMLSchema}hexBinary"/&amp;gt;
 * &amp;lt;/sequence&amp;gt;
 * &amp;lt;/extension&amp;gt;
 * &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ADDRDEF-PHYS-SEGMENT")
public class ADDRDEFPHYSSEGMENT
        extends PHYSSEGMENT {

    @XmlElement(name = "END-ADDRESS", required = true, type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    @XmlSchemaType(name = "hexBinary")
    protected byte[] endaddress;

    /**
     * Gets the value of the endaddress property.
     *
     * @return possible object is
     * {@link String }
     */
    public byte[] getENDADDRESS() {
        return endaddress;
    }

    /**
     * Sets the value of the endaddress property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setENDADDRESS(final byte[] value) {
        this.endaddress = value;
    }

}
