//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.28 at 09:58:19 AM CET 
//


package com.javahacks.odx.model;

import org.eclipse.persistence.oxm.annotations.XmlPath;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * &lt;p&gt;Java class for BASE-VARIANT complex type.
 * <p>
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * <p>
 * &lt;pre&gt;
 * &amp;lt;complexType name="BASE-VARIANT"&amp;gt;
 * &amp;lt;complexContent&amp;gt;
 * &amp;lt;extension base="{}HIERARCHY-ELEMENT"&amp;gt;
 * &amp;lt;sequence&amp;gt;
 * &amp;lt;element name="DIAG-VARIABLES" type="{}DIAG-VARIABLES" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="VARIABLE-GROUPS" type="{}VARIABLE-GROUPS" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="DYN-DEFINED-SPEC" type="{}DYN-DEFINED-SPEC" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="BASE-VARIANT-PATTERN" type="{}BASE-VARIANT-PATTERN" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="PARENT-REFS" type="{}PARENT-REFS" minOccurs="0"/&amp;gt;
 * &amp;lt;/sequence&amp;gt;
 * &amp;lt;/extension&amp;gt;
 * &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BASE-VARIANT")
public class BASEVARIANT
        extends HIERARCHYELEMENT {

    @XmlPath("BASE-VARIANT-PATTERN/MATCHING-BASE-VARIANT-PARAMETERS/MATCHING-BASE-VARIANT-PARAMETER")
    private final List<MATCHINGBASEVARIANTPARAMETER> matchingBasevariantParameters = new ArrayList<>();
    @XmlElement(name = "DIAG-VARIABLES")
    protected DIAGVARIABLES diagvariables;
    @XmlElement(name = "VARIABLE-GROUPS")
    protected VARIABLEGROUPS variablegroups;
    @XmlElement(name = "DYN-DEFINED-SPEC")
    protected DYNDEFINEDSPEC dyndefinedspec;

    /**
     * Gets the value of the diagvariables property.
     *
     * @return possible object is
     * {@link DIAGVARIABLES }
     */
    public DIAGVARIABLES getDIAGVARIABLES() {
        return diagvariables;
    }

    /**
     * Sets the value of the diagvariables property.
     *
     * @param value allowed object is
     *              {@link DIAGVARIABLES }
     */
    public void setDIAGVARIABLES(final DIAGVARIABLES value) {
        this.diagvariables = value;
    }

    /**
     * Gets the value of the variablegroups property.
     *
     * @return possible object is
     * {@link VARIABLEGROUPS }
     */
    public VARIABLEGROUPS getVARIABLEGROUPS() {
        return variablegroups;
    }

    /**
     * Sets the value of the variablegroups property.
     *
     * @param value allowed object is
     *              {@link VARIABLEGROUPS }
     */
    public void setVARIABLEGROUPS(final VARIABLEGROUPS value) {
        this.variablegroups = value;
    }

    /**
     * Gets the value of the dyndefinedspec property.
     *
     * @return possible object is
     * {@link DYNDEFINEDSPEC }
     */
    public DYNDEFINEDSPEC getDYNDEFINEDSPEC() {
        return dyndefinedspec;
    }

    /**
     * Sets the value of the dyndefinedspec property.
     *
     * @param value allowed object is
     *              {@link DYNDEFINEDSPEC }
     */
    public void setDYNDEFINEDSPEC(final DYNDEFINEDSPEC value) {
        this.dyndefinedspec = value;
    }


    public List<MATCHINGBASEVARIANTPARAMETER> getMatchingBasevariantParameters() {
        return matchingBasevariantParameters;
    }
}
