//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.28 at 09:58:19 AM CET 
//


package com.javahacks.odx.model;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * &lt;p&gt;Java class for BASE-FUNCTION-NODE complex type.
 * <p>
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * <p>
 * &lt;pre&gt;
 * &amp;lt;complexType name="BASE-FUNCTION-NODE"&amp;gt;
 * &amp;lt;complexContent&amp;gt;
 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 * &amp;lt;sequence&amp;gt;
 * &amp;lt;group ref="{}ELEMENT-ID"/&amp;gt;
 * &amp;lt;element name="AUDIENCE" type="{}AUDIENCE" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="FUNCTION-IN-PARAMS" type="{}FUNCTION-IN-PARAMS" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="FUNCTION-OUT-PARAMS" type="{}FUNCTION-OUT-PARAMS" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="COMPONENT-CONNECTORS" type="{}COMPONENT-CONNECTORS" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="MULTIPLE-ECU-JOB-REFS" type="{}MULTIPLE-ECU-JOB-REFS" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="ADMIN-DATA" type="{}ADMIN-DATA" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="SDG" type="{}SDG" minOccurs="0"/&amp;gt;
 * &amp;lt;/sequence&amp;gt;
 * &amp;lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" /&amp;gt;
 * &amp;lt;attribute name="OID" type="{http://www.w3.org/2001/XMLSchema}string" /&amp;gt;
 * &amp;lt;/restriction&amp;gt;
 * &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BASE-FUNCTION-NODE")
@XmlSeeAlso({
        FUNCTIONNODE.class,
        FUNCTIONNODEGROUP.class
})
public abstract class BASEFUNCTIONNODE {

    @XmlElement(name = "SHORT-NAME", required = true)
    protected String shortname;
    @XmlElement(name = "LONG-NAME")
    protected LONGNAME longname;
    @XmlElement(name = "DESC")
    protected DESCRIPTION desc;
    @XmlElement(name = "AUDIENCE")
    protected AUDIENCE audience;
    @XmlElement(name = "FUNCTION-IN-PARAMS")
    protected FUNCTIONINPARAMS functioninparams;
    @XmlElement(name = "FUNCTION-OUT-PARAMS")
    protected FUNCTIONOUTPARAMS functionoutparams;
    @XmlElement(name = "COMPONENT-CONNECTORS")
    protected COMPONENTCONNECTORS componentconnectors;
    @XmlElement(name = "MULTIPLE-ECU-JOB-REFS")
    protected MULTIPLEECUJOBREFS multipleecujobrefs;
    @XmlElement(name = "ADMIN-DATA")
    protected ADMINDATA admindata;
    @XmlElement(name = "SDG")
    protected SDG sdg;
    @XmlAttribute(name = "ID", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "OID")
    @XmlTransient
    protected String oid;

    /**
     * Gets the value of the shortname property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSHORTNAME() {
        return shortname;
    }

    /**
     * Sets the value of the shortname property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSHORTNAME(final String value) {
        this.shortname = value;
    }

    /**
     * Gets the value of the longname property.
     *
     * @return possible object is
     * {@link LONGNAME }
     */
    public LONGNAME getLONGNAME() {
        return longname;
    }

    /**
     * Sets the value of the longname property.
     *
     * @param value allowed object is
     *              {@link LONGNAME }
     */
    public void setLONGNAME(final LONGNAME value) {
        this.longname = value;
    }

    /**
     * Gets the value of the desc property.
     *
     * @return possible object is
     * {@link DESCRIPTION }
     */
    public DESCRIPTION getDESC() {
        return desc;
    }

    /**
     * Sets the value of the desc property.
     *
     * @param value allowed object is
     *              {@link DESCRIPTION }
     */
    public void setDESC(final DESCRIPTION value) {
        this.desc = value;
    }

    /**
     * Gets the value of the audience property.
     *
     * @return possible object is
     * {@link AUDIENCE }
     */
    public AUDIENCE getAUDIENCE() {
        return audience;
    }

    /**
     * Sets the value of the audience property.
     *
     * @param value allowed object is
     *              {@link AUDIENCE }
     */
    public void setAUDIENCE(final AUDIENCE value) {
        this.audience = value;
    }

    /**
     * Gets the value of the functioninparams property.
     *
     * @return possible object is
     * {@link FUNCTIONINPARAMS }
     */
    public FUNCTIONINPARAMS getFUNCTIONINPARAMS() {
        return functioninparams;
    }

    /**
     * Sets the value of the functioninparams property.
     *
     * @param value allowed object is
     *              {@link FUNCTIONINPARAMS }
     */
    public void setFUNCTIONINPARAMS(final FUNCTIONINPARAMS value) {
        this.functioninparams = value;
    }

    /**
     * Gets the value of the functionoutparams property.
     *
     * @return possible object is
     * {@link FUNCTIONOUTPARAMS }
     */
    public FUNCTIONOUTPARAMS getFUNCTIONOUTPARAMS() {
        return functionoutparams;
    }

    /**
     * Sets the value of the functionoutparams property.
     *
     * @param value allowed object is
     *              {@link FUNCTIONOUTPARAMS }
     */
    public void setFUNCTIONOUTPARAMS(final FUNCTIONOUTPARAMS value) {
        this.functionoutparams = value;
    }

    /**
     * Gets the value of the componentconnectors property.
     *
     * @return possible object is
     * {@link COMPONENTCONNECTORS }
     */
    public COMPONENTCONNECTORS getCOMPONENTCONNECTORS() {
        return componentconnectors;
    }

    /**
     * Sets the value of the componentconnectors property.
     *
     * @param value allowed object is
     *              {@link COMPONENTCONNECTORS }
     */
    public void setCOMPONENTCONNECTORS(final COMPONENTCONNECTORS value) {
        this.componentconnectors = value;
    }

    /**
     * Gets the value of the multipleecujobrefs property.
     *
     * @return possible object is
     * {@link MULTIPLEECUJOBREFS }
     */
    public MULTIPLEECUJOBREFS getMULTIPLEECUJOBREFS() {
        return multipleecujobrefs;
    }

    /**
     * Sets the value of the multipleecujobrefs property.
     *
     * @param value allowed object is
     *              {@link MULTIPLEECUJOBREFS }
     */
    public void setMULTIPLEECUJOBREFS(final MULTIPLEECUJOBREFS value) {
        this.multipleecujobrefs = value;
    }

    /**
     * Gets the value of the admindata property.
     *
     * @return possible object is
     * {@link ADMINDATA }
     */
    public ADMINDATA getADMINDATA() {
        return admindata;
    }

    /**
     * Sets the value of the admindata property.
     *
     * @param value allowed object is
     *              {@link ADMINDATA }
     */
    public void setADMINDATA(final ADMINDATA value) {
        this.admindata = value;
    }

    /**
     * Gets the value of the sdg property.
     *
     * @return possible object is
     * {@link SDG }
     */
    public SDG getSDG() {
        return sdg;
    }

    /**
     * Sets the value of the sdg property.
     *
     * @param value allowed object is
     *              {@link SDG }
     */
    public void setSDG(final SDG value) {
        this.sdg = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setID(final String value) {
        this.id = value;
    }

    /**
     * Gets the value of the oid property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getOID() {
        return oid;
    }

    /**
     * Sets the value of the oid property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setOID(final String value) {
        this.oid = value;
    }

}
