//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.28 at 09:58:19 AM CET 
//


package com.javahacks.odx.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for CODED-CONST complex type.
 * <p>
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * <p>
 * &lt;pre&gt;
 * &amp;lt;complexType name="CODED-CONST"&amp;gt;
 * &amp;lt;complexContent&amp;gt;
 * &amp;lt;extension base="{}POSITIONABLE-PARAM"&amp;gt;
 * &amp;lt;sequence&amp;gt;
 * &amp;lt;element name="CODED-VALUE" type="{http://www.w3.org/2001/XMLSchema}string"/&amp;gt;
 * &amp;lt;element name="DIAG-CODED-TYPE" type="{}DIAG-CODED-TYPE"/&amp;gt;
 * &amp;lt;/sequence&amp;gt;
 * &amp;lt;/extension&amp;gt;
 * &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CODED-CONST")
public class CODEDCONST
        extends POSITIONABLEPARAM {

    @XmlElement(name = "CODED-VALUE", required = true)
    protected String codedvalue;
    @XmlElement(name = "DIAG-CODED-TYPE", required = true)
    protected DIAGCODEDTYPE diagcodedtype;

    /**
     * Gets the value of the codedvalue property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCODEDVALUE() {
        return codedvalue;
    }

    /**
     * Sets the value of the codedvalue property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCODEDVALUE(String value) {
        this.codedvalue = value;
    }

    /**
     * Gets the value of the diagcodedtype property.
     *
     * @return possible object is
     * {@link DIAGCODEDTYPE }
     */
    public DIAGCODEDTYPE getDIAGCODEDTYPE() {
        return diagcodedtype;
    }

    /**
     * Sets the value of the diagcodedtype property.
     *
     * @param value allowed object is
     *              {@link DIAGCODEDTYPE }
     */
    public void setDIAGCODEDTYPE(DIAGCODEDTYPE value) {
        this.diagcodedtype = value;
    }

}
