//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.28 at 09:58:19 AM CET 
//


package com.javahacks.odx.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for COMPONENT-CONNECTOR complex type.
 * <p>
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * <p>
 * &lt;pre&gt;
 * &amp;lt;complexType name="COMPONENT-CONNECTOR"&amp;gt;
 * &amp;lt;complexContent&amp;gt;
 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 * &amp;lt;sequence&amp;gt;
 * &amp;lt;element name="ECU-VARIANT-REFS" type="{}ECU-VARIANT-REFS" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="BASE-VARIANT-REF" type="{}ODXLINK" minOccurs="0"/&amp;gt;
 * &amp;lt;choice&amp;gt;
 * &amp;lt;element name="DIAG-OBJECT-CONNECTOR" type="{}DIAG-OBJECT-CONNECTOR" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="DIAG-OBJECT-CONNECTOR-REF" type="{}ODXLINK" minOccurs="0"/&amp;gt;
 * &amp;lt;/choice&amp;gt;
 * &amp;lt;/sequence&amp;gt;
 * &amp;lt;/restriction&amp;gt;
 * &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "COMPONENT-CONNECTOR")
public class COMPONENTCONNECTOR {

    @XmlElement(name = "ECU-VARIANT-REFS")
    protected ECUVARIANTREFS ecuvariantrefs;
    @XmlElement(name = "BASE-VARIANT-REF")
    protected ODXLINK basevariantref;
    @XmlElement(name = "DIAG-OBJECT-CONNECTOR")
    protected DIAGOBJECTCONNECTOR diagobjectconnector;
    @XmlElement(name = "DIAG-OBJECT-CONNECTOR-REF")
    protected ODXLINK diagobjectconnectorref;

    /**
     * Gets the value of the ecuvariantrefs property.
     *
     * @return possible object is
     * {@link ECUVARIANTREFS }
     */
    public ECUVARIANTREFS getECUVARIANTREFS() {
        return ecuvariantrefs;
    }

    /**
     * Sets the value of the ecuvariantrefs property.
     *
     * @param value allowed object is
     *              {@link ECUVARIANTREFS }
     */
    public void setECUVARIANTREFS(ECUVARIANTREFS value) {
        this.ecuvariantrefs = value;
    }

    /**
     * Gets the value of the basevariantref property.
     *
     * @return possible object is
     * {@link ODXLINK }
     */
    public ODXLINK getBASEVARIANTREF() {
        return basevariantref;
    }

    /**
     * Sets the value of the basevariantref property.
     *
     * @param value allowed object is
     *              {@link ODXLINK }
     */
    public void setBASEVARIANTREF(ODXLINK value) {
        this.basevariantref = value;
    }

    /**
     * Gets the value of the diagobjectconnector property.
     *
     * @return possible object is
     * {@link DIAGOBJECTCONNECTOR }
     */
    public DIAGOBJECTCONNECTOR getDIAGOBJECTCONNECTOR() {
        return diagobjectconnector;
    }

    /**
     * Sets the value of the diagobjectconnector property.
     *
     * @param value allowed object is
     *              {@link DIAGOBJECTCONNECTOR }
     */
    public void setDIAGOBJECTCONNECTOR(DIAGOBJECTCONNECTOR value) {
        this.diagobjectconnector = value;
    }

    /**
     * Gets the value of the diagobjectconnectorref property.
     *
     * @return possible object is
     * {@link ODXLINK }
     */
    public ODXLINK getDIAGOBJECTCONNECTORREF() {
        return diagobjectconnectorref;
    }

    /**
     * Sets the value of the diagobjectconnectorref property.
     *
     * @param value allowed object is
     *              {@link ODXLINK }
     */
    public void setDIAGOBJECTCONNECTORREF(ODXLINK value) {
        this.diagobjectconnectorref = value;
    }

}
