//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.28 at 09:58:19 AM CET 
//


package com.javahacks.odx.model;

import org.eclipse.persistence.oxm.annotations.XmlPath;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * &lt;p&gt;Java class for COMPLEX-COMPARAM complex type.
 * <p>
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * <p>
 * &lt;pre&gt;
 * &amp;lt;complexType name="COMPLEX-COMPARAM"&amp;gt;
 * &amp;lt;complexContent&amp;gt;
 * &amp;lt;extension base="{}BASE-COMPARAM"&amp;gt;
 * &amp;lt;sequence&amp;gt;
 * &amp;lt;choice maxOccurs="unbounded"&amp;gt;
 * &amp;lt;element name="COMPARAM" type="{}COMPARAM"/&amp;gt;
 * &amp;lt;element name="COMPLEX-COMPARAM" type="{}COMPLEX-COMPARAM"/&amp;gt;
 * &amp;lt;/choice&amp;gt;
 * &amp;lt;element name="COMPLEX-PHYSICAL-DEFAULT-VALUE" type="{}COMPLEX-PHYSICAL-DEFAULT-VALUE" minOccurs="0"/&amp;gt;
 * &amp;lt;/sequence&amp;gt;
 * &amp;lt;attribute name="ALLOW-MULTIPLE-VALUES" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&amp;gt;
 * &amp;lt;/extension&amp;gt;
 * &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "COMPLEX-COMPARAM")
public class COMPLEXCOMPARAM
        extends BASECOMPARAM {

    @XmlElements({
            @XmlElement(name = "COMPARAM", type = COMPARAM.class),
            @XmlElement(name = "COMPLEX-COMPARAM", type = COMPLEXCOMPARAM.class)
    })
    protected List<BASECOMPARAM> comparamOrCOMPLEXCOMPARAM;
    @XmlPath("COMPLEX-PHYSICAL-DEFAULT-VALUE/COMPLEX-VALUES")
    protected COMPLEXVALUE complexphysicaldefaultvalues;
    @XmlAttribute(name = "ALLOW-MULTIPLE-VALUES")
    protected Boolean allowmultiplevalues;

    /**
     * Gets the value of the comparamOrCOMPLEXCOMPARAM property.
     * <p>
     * &lt;p&gt;
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a &lt;CODE&gt;set&lt;/CODE&gt; method for the comparamOrCOMPLEXCOMPARAM property.
     * <p>
     * &lt;p&gt;
     * For example, to add a new item, do as follows:
     * &lt;pre&gt;
     * getCOMPARAMOrCOMPLEXCOMPARAM().add(newItem);
     * &lt;/pre&gt;
     * <p>
     * <p>
     * &lt;p&gt;
     * Objects of the following type(s) are allowed in the list
     * {@link COMPARAM }
     * {@link COMPLEXCOMPARAM }
     */
    public List<BASECOMPARAM> getCOMPARAMOrCOMPLEXCOMPARAM() {
        if (comparamOrCOMPLEXCOMPARAM == null) {
            comparamOrCOMPLEXCOMPARAM = new ArrayList<BASECOMPARAM>();
        }
        return this.comparamOrCOMPLEXCOMPARAM;
    }


    /**
     * Gets the value of the allowmultiplevalues property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public boolean isALLOWMULTIPLEVALUES() {
        if (allowmultiplevalues == null) {
            return false;
        } else {
            return allowmultiplevalues;
        }
    }

    /**
     * Sets the value of the allowmultiplevalues property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setALLOWMULTIPLEVALUES(final Boolean value) {
        this.allowmultiplevalues = value;
    }

    public COMPLEXVALUE getComplexphysicaldefaultvalues() {
        return complexphysicaldefaultvalues;
    }

    public void setComplexphysicaldefaultvalues(final COMPLEXVALUE complexphysicaldefaultvalues) {
        this.complexphysicaldefaultvalues = complexphysicaldefaultvalues;
    }
}
