//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.28 at 09:58:19 AM CET 
//


package com.javahacks.odx.model;

import javax.xml.bind.annotation.*;


/**
 * &lt;p&gt;Java class for COMPU-METHOD complex type.
 * <p>
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * <p>
 * &lt;pre&gt;
 * &amp;lt;complexType name="COMPU-METHOD"&amp;gt;
 * &amp;lt;complexContent&amp;gt;
 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 * &amp;lt;sequence&amp;gt;
 * &amp;lt;element name="CATEGORY" type="{}COMPU-CATEGORY"/&amp;gt;
 * &amp;lt;element name="COMPU-INTERNAL-TO-PHYS" type="{}COMPU-INTERNAL-TO-PHYS" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="COMPU-PHYS-TO-INTERNAL" type="{}COMPU-PHYS-TO-INTERNAL" minOccurs="0"/&amp;gt;
 * &amp;lt;/sequence&amp;gt;
 * &amp;lt;/restriction&amp;gt;
 * &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "COMPU-METHOD")
public class COMPUMETHOD {

    @XmlElement(name = "CATEGORY", required = true)
    @XmlSchemaType(name = "string")
    protected COMPUCATEGORY category;
    @XmlElement(name = "COMPU-INTERNAL-TO-PHYS")
    protected COMPUINTERNALTOPHYS compuinternaltophys;
    @XmlElement(name = "COMPU-PHYS-TO-INTERNAL")
    protected COMPUPHYSTOINTERNAL compuphystointernal;

    /**
     * Gets the value of the category property.
     *
     * @return possible object is
     * {@link COMPUCATEGORY }
     */
    public COMPUCATEGORY getCATEGORY() {
        return category;
    }

    /**
     * Sets the value of the category property.
     *
     * @param value allowed object is
     *              {@link COMPUCATEGORY }
     */
    public void setCATEGORY(COMPUCATEGORY value) {
        this.category = value;
    }

    /**
     * Gets the value of the compuinternaltophys property.
     *
     * @return possible object is
     * {@link COMPUINTERNALTOPHYS }
     */
    public COMPUINTERNALTOPHYS getCOMPUINTERNALTOPHYS() {
        return compuinternaltophys;
    }

    /**
     * Sets the value of the compuinternaltophys property.
     *
     * @param value allowed object is
     *              {@link COMPUINTERNALTOPHYS }
     */
    public void setCOMPUINTERNALTOPHYS(COMPUINTERNALTOPHYS value) {
        this.compuinternaltophys = value;
    }

    /**
     * Gets the value of the compuphystointernal property.
     *
     * @return possible object is
     * {@link COMPUPHYSTOINTERNAL }
     */
    public COMPUPHYSTOINTERNAL getCOMPUPHYSTOINTERNAL() {
        return compuphystointernal;
    }

    /**
     * Sets the value of the compuphystointernal property.
     *
     * @param value allowed object is
     *              {@link COMPUPHYSTOINTERNAL }
     */
    public void setCOMPUPHYSTOINTERNAL(COMPUPHYSTOINTERNAL value) {
        this.compuphystointernal = value;
    }

}
