//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.28 at 09:58:19 AM CET 
//


package com.javahacks.odx.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for COMPU-INVERSE-VALUE complex type.
 * <p>
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * <p>
 * &lt;pre&gt;
 * &amp;lt;complexType name="COMPU-INVERSE-VALUE"&amp;gt;
 * &amp;lt;complexContent&amp;gt;
 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 * &amp;lt;choice&amp;gt;
 * &amp;lt;element name="V" type="{}V"/&amp;gt;
 * &amp;lt;element name="VT" type="{}VT"/&amp;gt;
 * &amp;lt;/choice&amp;gt;
 * &amp;lt;/restriction&amp;gt;
 * &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "COMPU-INVERSE-VALUE")
public class COMPUINVERSEVALUE {

    @XmlElement(name = "V")
    protected V v;
    @XmlElement(name = "VT")
    protected VT vt;

    /**
     * Gets the value of the v property.
     *
     * @return possible object is
     * {@link V }
     */
    public V getV() {
        return v;
    }

    /**
     * Sets the value of the v property.
     *
     * @param value allowed object is
     *              {@link V }
     */
    public void setV(V value) {
        this.v = value;
    }

    /**
     * Gets the value of the vt property.
     *
     * @return possible object is
     * {@link VT }
     */
    public VT getVT() {
        return vt;
    }

    /**
     * Sets the value of the vt property.
     *
     * @param value allowed object is
     *              {@link VT }
     */
    public void setVT(VT value) {
        this.vt = value;
    }

}
