//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.28 at 09:58:19 AM CET 
//


package com.javahacks.odx.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for COMPU-RATIONAL-COEFFS complex type.
 * <p>
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * <p>
 * &lt;pre&gt;
 * &amp;lt;complexType name="COMPU-RATIONAL-COEFFS"&amp;gt;
 * &amp;lt;complexContent&amp;gt;
 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 * &amp;lt;sequence&amp;gt;
 * &amp;lt;element name="COMPU-NUMERATOR" type="{}COMPU-NUMERATOR"/&amp;gt;
 * &amp;lt;element name="COMPU-DENOMINATOR" type="{}COMPU-DENOMINATOR" minOccurs="0"/&amp;gt;
 * &amp;lt;/sequence&amp;gt;
 * &amp;lt;/restriction&amp;gt;
 * &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "COMPU-RATIONAL-COEFFS")
public class COMPURATIONALCOEFFS {

    @XmlElement(name = "COMPU-NUMERATOR", required = true)
    protected COMPUNUMERATOR compunumerator;
    @XmlElement(name = "COMPU-DENOMINATOR")
    protected COMPUDENOMINATOR compudenominator;

    /**
     * Gets the value of the compunumerator property.
     *
     * @return possible object is
     * {@link COMPUNUMERATOR }
     */
    public COMPUNUMERATOR getCOMPUNUMERATOR() {
        return compunumerator;
    }

    /**
     * Sets the value of the compunumerator property.
     *
     * @param value allowed object is
     *              {@link COMPUNUMERATOR }
     */
    public void setCOMPUNUMERATOR(COMPUNUMERATOR value) {
        this.compunumerator = value;
    }

    /**
     * Gets the value of the compudenominator property.
     *
     * @return possible object is
     * {@link COMPUDENOMINATOR }
     */
    public COMPUDENOMINATOR getCOMPUDENOMINATOR() {
        return compudenominator;
    }

    /**
     * Sets the value of the compudenominator property.
     *
     * @param value allowed object is
     *              {@link COMPUDENOMINATOR }
     */
    public void setCOMPUDENOMINATOR(COMPUDENOMINATOR value) {
        this.compudenominator = value;
    }

}
