//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.28 at 09:58:19 AM CET 
//


package com.javahacks.odx.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for COMPANY-DOC-INFO complex type.
 * <p>
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * <p>
 * &lt;pre&gt;
 * &amp;lt;complexType name="COMPANY-DOC-INFO"&amp;gt;
 * &amp;lt;complexContent&amp;gt;
 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 * &amp;lt;sequence&amp;gt;
 * &amp;lt;element name="COMPANY-DATA-REF" type="{}ODXLINK"/&amp;gt;
 * &amp;lt;element name="TEAM-MEMBER-REF" type="{}ODXLINK" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="DOC-LABEL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="SDGS" type="{}SDGS" minOccurs="0"/&amp;gt;
 * &amp;lt;/sequence&amp;gt;
 * &amp;lt;/restriction&amp;gt;
 * &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "COMPANY-DOC-INFO")
public class COMPANYDOCINFO {

    @XmlElement(name = "COMPANY-DATA-REF", required = true)
    protected ODXLINK companydataref;
    @XmlElement(name = "TEAM-MEMBER-REF")
    protected ODXLINK teammemberref;
    @XmlElement(name = "DOC-LABEL")
    protected String doclabel;
    @XmlElement(name = "SDGS")
    protected SDGS sdgs;

    /**
     * Gets the value of the companydataref property.
     *
     * @return possible object is
     * {@link ODXLINK }
     */
    public ODXLINK getCOMPANYDATAREF() {
        return companydataref;
    }

    /**
     * Sets the value of the companydataref property.
     *
     * @param value allowed object is
     *              {@link ODXLINK }
     */
    public void setCOMPANYDATAREF(ODXLINK value) {
        this.companydataref = value;
    }

    /**
     * Gets the value of the teammemberref property.
     *
     * @return possible object is
     * {@link ODXLINK }
     */
    public ODXLINK getTEAMMEMBERREF() {
        return teammemberref;
    }

    /**
     * Sets the value of the teammemberref property.
     *
     * @param value allowed object is
     *              {@link ODXLINK }
     */
    public void setTEAMMEMBERREF(ODXLINK value) {
        this.teammemberref = value;
    }

    /**
     * Gets the value of the doclabel property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDOCLABEL() {
        return doclabel;
    }

    /**
     * Sets the value of the doclabel property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDOCLABEL(String value) {
        this.doclabel = value;
    }

    /**
     * Gets the value of the sdgs property.
     *
     * @return possible object is
     * {@link SDGS }
     */
    public SDGS getSDGS() {
        return sdgs;
    }

    /**
     * Sets the value of the sdgs property.
     *
     * @param value allowed object is
     *              {@link SDGS }
     */
    public void setSDGS(SDGS value) {
        this.sdgs = value;
    }

}
