//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.28 at 09:58:19 AM CET 
//


package com.javahacks.odx.model;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * &lt;p&gt;Java class for COMPLEX-VALUE complex type.
 * <p>
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * <p>
 * &lt;pre&gt;
 * &amp;lt;complexType name="COMPLEX-VALUE"&amp;gt;
 * &amp;lt;complexContent&amp;gt;
 * &amp;lt;extension base="{}BASE-VALUE"&amp;gt;
 * &amp;lt;choice maxOccurs="unbounded"&amp;gt;
 * &amp;lt;element name="SIMPLE-VALUE" type="{}SIMPLE-VALUE"/&amp;gt;
 * &amp;lt;element name="COMPLEX-VALUE" type="{}COMPLEX-VALUE"/&amp;gt;
 * &amp;lt;/choice&amp;gt;
 * &amp;lt;/extension&amp;gt;
 * &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "COMPLEX-VALUE")
public class COMPLEXVALUE
        extends BASEVALUE {

    @XmlElements({
            @XmlElement(name = "SIMPLE-VALUE", type = SIMPLEVALUE.class),
            @XmlElement(name = "COMPLEX-VALUE", type = COMPLEXVALUE.class)
    })
    protected List<Object> simplevalueOrCOMPLEXVALUE;

    /**
     * Gets the value of the simplevalueOrCOMPLEXVALUE property.
     * <p>
     * &lt;p&gt;
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a &lt;CODE&gt;set&lt;/CODE&gt; method for the simplevalueOrCOMPLEXVALUE property.
     * <p>
     * &lt;p&gt;
     * For example, to add a new item, do as follows:
     * &lt;pre&gt;
     * getSIMPLEVALUEOrCOMPLEXVALUE().add(newItem);
     * &lt;/pre&gt;
     * <p>
     * <p>
     * &lt;p&gt;
     * Objects of the following type(s) are allowed in the list
     * {@link SIMPLEVALUE }
     * {@link COMPLEXVALUE }
     */
    public List<Object> getSIMPLEVALUEOrCOMPLEXVALUE() {
        if (simplevalueOrCOMPLEXVALUE == null) {
            simplevalueOrCOMPLEXVALUE = new ArrayList<Object>();
        }
        return this.simplevalueOrCOMPLEXVALUE;
    }

}
