//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.28 at 09:58:19 AM CET 
//


package com.javahacks.odx.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for CONFIG-DATA complex type.
 * <p>
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * <p>
 * &lt;pre&gt;
 * &amp;lt;complexType name="CONFIG-DATA"&amp;gt;
 * &amp;lt;complexContent&amp;gt;
 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 * &amp;lt;sequence&amp;gt;
 * &amp;lt;group ref="{}ELEMENT-ID"/&amp;gt;
 * &amp;lt;element name="VALID-BASE-VARIANTS" type="{}VALID-BASE-VARIANTS"/&amp;gt;
 * &amp;lt;element name="CONFIG-RECORDS" type="{}CONFIG-RECORDS" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="SDGS" type="{}SDGS" minOccurs="0"/&amp;gt;
 * &amp;lt;/sequence&amp;gt;
 * &amp;lt;/restriction&amp;gt;
 * &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CONFIG-DATA")
public class CONFIGDATA {

    @XmlElement(name = "SHORT-NAME", required = true)
    protected String shortname;
    @XmlElement(name = "LONG-NAME")
    protected LONGNAME longname;
    @XmlElement(name = "DESC")
    protected DESCRIPTION desc;
    @XmlElement(name = "VALID-BASE-VARIANTS", required = true)
    protected VALIDBASEVARIANTS validbasevariants;
    @XmlElement(name = "CONFIG-RECORDS")
    protected CONFIGRECORDS configrecords;
    @XmlElement(name = "SDGS")
    protected SDGS sdgs;

    /**
     * Gets the value of the shortname property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSHORTNAME() {
        return shortname;
    }

    /**
     * Sets the value of the shortname property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSHORTNAME(String value) {
        this.shortname = value;
    }

    /**
     * Gets the value of the longname property.
     *
     * @return possible object is
     * {@link LONGNAME }
     */
    public LONGNAME getLONGNAME() {
        return longname;
    }

    /**
     * Sets the value of the longname property.
     *
     * @param value allowed object is
     *              {@link LONGNAME }
     */
    public void setLONGNAME(LONGNAME value) {
        this.longname = value;
    }

    /**
     * Gets the value of the desc property.
     *
     * @return possible object is
     * {@link DESCRIPTION }
     */
    public DESCRIPTION getDESC() {
        return desc;
    }

    /**
     * Sets the value of the desc property.
     *
     * @param value allowed object is
     *              {@link DESCRIPTION }
     */
    public void setDESC(DESCRIPTION value) {
        this.desc = value;
    }

    /**
     * Gets the value of the validbasevariants property.
     *
     * @return possible object is
     * {@link VALIDBASEVARIANTS }
     */
    public VALIDBASEVARIANTS getVALIDBASEVARIANTS() {
        return validbasevariants;
    }

    /**
     * Sets the value of the validbasevariants property.
     *
     * @param value allowed object is
     *              {@link VALIDBASEVARIANTS }
     */
    public void setVALIDBASEVARIANTS(VALIDBASEVARIANTS value) {
        this.validbasevariants = value;
    }

    /**
     * Gets the value of the configrecords property.
     *
     * @return possible object is
     * {@link CONFIGRECORDS }
     */
    public CONFIGRECORDS getCONFIGRECORDS() {
        return configrecords;
    }

    /**
     * Sets the value of the configrecords property.
     *
     * @param value allowed object is
     *              {@link CONFIGRECORDS }
     */
    public void setCONFIGRECORDS(CONFIGRECORDS value) {
        this.configrecords = value;
    }

    /**
     * Gets the value of the sdgs property.
     *
     * @return possible object is
     * {@link SDGS }
     */
    public SDGS getSDGS() {
        return sdgs;
    }

    /**
     * Sets the value of the sdgs property.
     *
     * @param value allowed object is
     *              {@link SDGS }
     */
    public void setSDGS(SDGS value) {
        this.sdgs = value;
    }

}
