//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.28 at 09:58:19 AM CET 
//


package com.javahacks.odx.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for DATAFORMAT-SELECTION.
 * <p>
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * &lt;pre&gt;
 * &amp;lt;simpleType name="DATAFORMAT-SELECTION"&amp;gt;
 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt;
 * &amp;lt;enumeration value="INTEL-HEX"/&amp;gt;
 * &amp;lt;enumeration value="MOTOROLA-S"/&amp;gt;
 * &amp;lt;enumeration value="BINARY"/&amp;gt;
 * &amp;lt;enumeration value="USER-DEFINED"/&amp;gt;
 * &amp;lt;/restriction&amp;gt;
 * &amp;lt;/simpleType&amp;gt;
 * &lt;/pre&gt;
 */
@XmlType(name = "DATAFORMAT-SELECTION")
@XmlEnum
public enum DATAFORMATSELECTION {

    @XmlEnumValue("INTEL-HEX")
    INTEL_HEX("INTEL-HEX"),
    @XmlEnumValue("MOTOROLA-S")
    MOTOROLA_S("MOTOROLA-S"),
    BINARY("BINARY"),
    @XmlEnumValue("USER-DEFINED")
    USER_DEFINED("USER-DEFINED");
    private final String value;

    DATAFORMATSELECTION(final String v) {
        value = v;
    }

    public static DATAFORMATSELECTION fromValue(final String v) {
        for (final DATAFORMATSELECTION c : DATAFORMATSELECTION.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

    public String value() {
        return value;
    }

}
