//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.28 at 09:58:19 AM CET 
//


package com.javahacks.odx.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for DATA-TYPE.
 * <p>
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * &lt;pre&gt;
 * &amp;lt;simpleType name="DATA-TYPE"&amp;gt;
 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt;
 * &amp;lt;enumeration value="A_INT32"/&amp;gt;
 * &amp;lt;enumeration value="A_UINT32"/&amp;gt;
 * &amp;lt;enumeration value="A_FLOAT32"/&amp;gt;
 * &amp;lt;enumeration value="A_FLOAT64"/&amp;gt;
 * &amp;lt;enumeration value="A_ASCIISTRING"/&amp;gt;
 * &amp;lt;enumeration value="A_UTF8STRING"/&amp;gt;
 * &amp;lt;enumeration value="A_UNICODE2STRING"/&amp;gt;
 * &amp;lt;enumeration value="A_BYTEFIELD"/&amp;gt;
 * &amp;lt;/restriction&amp;gt;
 * &amp;lt;/simpleType&amp;gt;
 * &lt;/pre&gt;
 */
@XmlType(name = "DATA-TYPE")
@XmlEnum
public enum DATATYPE {

    @XmlEnumValue("A_INT32")
    A_INT_32("A_INT32"),
    @XmlEnumValue("A_UINT32")
    A_UINT_32("A_UINT32"),
    @XmlEnumValue("A_FLOAT32")
    A_FLOAT_32("A_FLOAT32"),
    @XmlEnumValue("A_FLOAT64")
    A_FLOAT_64("A_FLOAT64"),
    A_ASCIISTRING("A_ASCIISTRING"),
    @XmlEnumValue("A_UTF8STRING")
    A_UTF_8_STRING("A_UTF8STRING"),
    @XmlEnumValue("A_UNICODE2STRING")
    A_UNICODE_2_STRING("A_UNICODE2STRING"),
    A_BYTEFIELD("A_BYTEFIELD");
    private final String value;

    DATATYPE(String v) {
        value = v;
    }

    public static DATATYPE fromValue(String v) {
        for (DATATYPE c : DATATYPE.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

    public String value() {
        return value;
    }

}
