//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.28 at 09:58:19 AM CET 
//


package com.javahacks.odx.model;

import com.javahacks.odx.index.LocationAware;
import com.javahacks.odx.index.XmlElementLocation;

import javax.xml.bind.annotation.*;


/**
 * &lt;p&gt;Java class for DATAFILE complex type.
 * <p>
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * <p>
 * &lt;pre&gt;
 * &amp;lt;complexType name="DATAFILE"&amp;gt;
 * &amp;lt;simpleContent&amp;gt;
 * &amp;lt;extension base="&amp;lt;http://www.w3.org/2001/XMLSchema&amp;gt;string"&amp;gt;
 * &amp;lt;attribute name="LATEBOUND-DATAFILE" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&amp;gt;
 * &amp;lt;/extension&amp;gt;
 * &amp;lt;/simpleContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DATAFILE")
public class DATAFILE implements LocationAware {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "LATEBOUND-DATAFILE", required = true)
    protected boolean latebounddatafile;

    @XmlTransient
    private XmlElementLocation position;

    /**
     * Gets the value of the value property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setValue(final String value) {
        this.value = value;
    }

    /**
     * Gets the value of the latebounddatafile property.
     */
    public boolean isLATEBOUNDDATAFILE() {
        return latebounddatafile;
    }

    /**
     * Sets the value of the latebounddatafile property.
     */
    public void setLATEBOUNDDATAFILE(final boolean value) {
        this.latebounddatafile = value;
    }

    @Override
    public XmlElementLocation getLocation() {
        return position;
    }

    @Override
    public void setLocation(final XmlElementLocation location) {
        this.position = location;
    }
}
