//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.28 at 09:58:19 AM CET 
//


package com.javahacks.odx.model;

import javax.xml.bind.annotation.*;


/**
 * &lt;p&gt;Java class for DETERMINE-NUMBER-OF-ITEMS complex type.
 * <p>
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * <p>
 * &lt;pre&gt;
 * &amp;lt;complexType name="DETERMINE-NUMBER-OF-ITEMS"&amp;gt;
 * &amp;lt;complexContent&amp;gt;
 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 * &amp;lt;sequence&amp;gt;
 * &amp;lt;element name="BYTE-POSITION" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/&amp;gt;
 * &amp;lt;element name="BIT-POSITION" minOccurs="0"&amp;gt;
 * &amp;lt;simpleType&amp;gt;
 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedInt"&amp;gt;
 * &amp;lt;maxExclusive value="8"/&amp;gt;
 * &amp;lt;/restriction&amp;gt;
 * &amp;lt;/simpleType&amp;gt;
 * &amp;lt;/element&amp;gt;
 * &amp;lt;element name="DATA-OBJECT-PROP-REF" type="{}ODXLINK"/&amp;gt;
 * &amp;lt;/sequence&amp;gt;
 * &amp;lt;/restriction&amp;gt;
 * &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DETERMINE-NUMBER-OF-ITEMS")
public class DETERMINENUMBEROFITEMS {

    @XmlElement(name = "BYTE-POSITION")
    @XmlSchemaType(name = "unsignedInt")
    protected long byteposition;
    @XmlElement(name = "BIT-POSITION")
    protected Long bitposition;
    @XmlElement(name = "DATA-OBJECT-PROP-REF", required = true)
    protected ODXLINK dataobjectpropref;

    /**
     * Gets the value of the byteposition property.
     */
    public long getBYTEPOSITION() {
        return byteposition;
    }

    /**
     * Sets the value of the byteposition property.
     */
    public void setBYTEPOSITION(final long value) {
        this.byteposition = value;
    }

    /**
     * Gets the value of the bitposition property.
     *
     * @return possible object is
     * {@link Long }
     */
    public Long getBITPOSITION() {
        return bitposition;
    }

    /**
     * Sets the value of the bitposition property.
     *
     * @param value allowed object is
     *              {@link Long }
     */
    public void setBITPOSITION(final Long value) {
        this.bitposition = value;
    }

    /**
     * Gets the value of the dataobjectpropref property.
     *
     * @return possible object is
     * {@link ODXLINK }
     */
    public ODXLINK getDATAOBJECTPROPREF() {
        return dataobjectpropref;
    }

    /**
     * Sets the value of the dataobjectpropref property.
     *
     * @param value allowed object is
     *              {@link ODXLINK }
     */
    public void setDATAOBJECTPROPREF(final ODXLINK value) {
        this.dataobjectpropref = value;
    }

}
