//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.28 at 09:58:19 AM CET 
//


package com.javahacks.odx.model;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * &lt;p&gt;Java class for DIAG-OBJECT-CONNECTOR complex type.
 * <p>
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * <p>
 * &lt;pre&gt;
 * &amp;lt;complexType name="DIAG-OBJECT-CONNECTOR"&amp;gt;
 * &amp;lt;complexContent&amp;gt;
 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 * &amp;lt;sequence&amp;gt;
 * &amp;lt;group ref="{}ELEMENT-ID"/&amp;gt;
 * &amp;lt;element name="FUNCTION-DIAG-COMM-CONNECTORS" type="{}FUNCTION-DIAG-COMM-CONNECTORS" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="TABLE-ROW-CONNECTORS" type="{}TABLE-ROW-CONNECTORS" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="ENV-DATA-CONNECTORS" type="{}ENV-DATA-CONNECTORS" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="DTC-CONNECTORS" type="{}DTC-CONNECTORS" minOccurs="0"/&amp;gt;
 * &amp;lt;/sequence&amp;gt;
 * &amp;lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" /&amp;gt;
 * &amp;lt;attribute name="OID" type="{http://www.w3.org/2001/XMLSchema}string" /&amp;gt;
 * &amp;lt;/restriction&amp;gt;
 * &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DIAG-OBJECT-CONNECTOR")
public class DIAGOBJECTCONNECTOR {

    @XmlElement(name = "SHORT-NAME", required = true)
    protected String shortname;
    @XmlElement(name = "LONG-NAME")
    protected LONGNAME longname;
    @XmlElement(name = "DESC")
    protected DESCRIPTION desc;
    @XmlElement(name = "FUNCTION-DIAG-COMM-CONNECTORS")
    protected FUNCTIONDIAGCOMMCONNECTORS functiondiagcommconnectors;
    @XmlElement(name = "TABLE-ROW-CONNECTORS")
    protected TABLEROWCONNECTORS tablerowconnectors;
    @XmlElement(name = "ENV-DATA-CONNECTORS")
    protected ENVDATACONNECTORS envdataconnectors;
    @XmlElement(name = "DTC-CONNECTORS")
    protected DTCCONNECTORS dtcconnectors;
    @XmlAttribute(name = "ID", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "OID")
    @XmlTransient
    protected String oid;

    /**
     * Gets the value of the shortname property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSHORTNAME() {
        return shortname;
    }

    /**
     * Sets the value of the shortname property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSHORTNAME(final String value) {
        this.shortname = value;
    }

    /**
     * Gets the value of the longname property.
     *
     * @return possible object is
     * {@link LONGNAME }
     */
    public LONGNAME getLONGNAME() {
        return longname;
    }

    /**
     * Sets the value of the longname property.
     *
     * @param value allowed object is
     *              {@link LONGNAME }
     */
    public void setLONGNAME(final LONGNAME value) {
        this.longname = value;
    }

    /**
     * Gets the value of the desc property.
     *
     * @return possible object is
     * {@link DESCRIPTION }
     */
    public DESCRIPTION getDESC() {
        return desc;
    }

    /**
     * Sets the value of the desc property.
     *
     * @param value allowed object is
     *              {@link DESCRIPTION }
     */
    public void setDESC(final DESCRIPTION value) {
        this.desc = value;
    }

    /**
     * Gets the value of the functiondiagcommconnectors property.
     *
     * @return possible object is
     * {@link FUNCTIONDIAGCOMMCONNECTORS }
     */
    public FUNCTIONDIAGCOMMCONNECTORS getFUNCTIONDIAGCOMMCONNECTORS() {
        return functiondiagcommconnectors;
    }

    /**
     * Sets the value of the functiondiagcommconnectors property.
     *
     * @param value allowed object is
     *              {@link FUNCTIONDIAGCOMMCONNECTORS }
     */
    public void setFUNCTIONDIAGCOMMCONNECTORS(final FUNCTIONDIAGCOMMCONNECTORS value) {
        this.functiondiagcommconnectors = value;
    }

    /**
     * Gets the value of the tablerowconnectors property.
     *
     * @return possible object is
     * {@link TABLEROWCONNECTORS }
     */
    public TABLEROWCONNECTORS getTABLEROWCONNECTORS() {
        return tablerowconnectors;
    }

    /**
     * Sets the value of the tablerowconnectors property.
     *
     * @param value allowed object is
     *              {@link TABLEROWCONNECTORS }
     */
    public void setTABLEROWCONNECTORS(final TABLEROWCONNECTORS value) {
        this.tablerowconnectors = value;
    }

    /**
     * Gets the value of the envdataconnectors property.
     *
     * @return possible object is
     * {@link ENVDATACONNECTORS }
     */
    public ENVDATACONNECTORS getENVDATACONNECTORS() {
        return envdataconnectors;
    }

    /**
     * Sets the value of the envdataconnectors property.
     *
     * @param value allowed object is
     *              {@link ENVDATACONNECTORS }
     */
    public void setENVDATACONNECTORS(final ENVDATACONNECTORS value) {
        this.envdataconnectors = value;
    }

    /**
     * Gets the value of the dtcconnectors property.
     *
     * @return possible object is
     * {@link DTCCONNECTORS }
     */
    public DTCCONNECTORS getDTCCONNECTORS() {
        return dtcconnectors;
    }

    /**
     * Sets the value of the dtcconnectors property.
     *
     * @param value allowed object is
     *              {@link DTCCONNECTORS }
     */
    public void setDTCCONNECTORS(final DTCCONNECTORS value) {
        this.dtcconnectors = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setID(final String value) {
        this.id = value;
    }

    /**
     * Gets the value of the oid property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getOID() {
        return oid;
    }

    /**
     * Sets the value of the oid property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setOID(final String value) {
        this.oid = value;
    }

}
