//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.28 at 09:58:19 AM CET 
//


package com.javahacks.odx.model;

import com.javahacks.odx.index.AbstractLinkTarget;
import com.javahacks.odx.index.Layer;
import com.javahacks.odx.index.LayerAware;
import org.eclipse.persistence.oxm.annotations.XmlPath;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;


/**
 * &lt;p&gt;Java class for DIAG-COMM complex type.
 * <p>
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * <p>
 * &lt;pre&gt;
 * &amp;lt;complexType name="DIAG-COMM"&amp;gt;
 * &amp;lt;complexContent&amp;gt;
 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 * &amp;lt;sequence&amp;gt;
 * &amp;lt;group ref="{}ELEMENT-ID"/&amp;gt;
 * &amp;lt;element name="ADMIN-DATA" type="{}ADMIN-DATA" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="SDGS" type="{}SDGS" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="FUNCT-CLASS-REFS" type="{}FUNCT-CLASS-REFS" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="AUDIENCE" type="{}AUDIENCE" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="PROTOCOL-SNREFS" type="{}PROTOCOL-SNREFS" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="RELATED-DIAG-COMM-REFS" type="{}RELATED-DIAG-COMM-REFS" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="PRE-CONDITION-STATE-REFS" type="{}PRE-CONDITION-STATE-REFS" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="STATE-TRANSITION-REFS" type="{}STATE-TRANSITION-REFS" minOccurs="0"/&amp;gt;
 * &amp;lt;/sequence&amp;gt;
 * &amp;lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" /&amp;gt;
 * &amp;lt;attribute name="OID" type="{http://www.w3.org/2001/XMLSchema}string" /&amp;gt;
 * &amp;lt;attribute name="SEMANTIC" type="{http://www.w3.org/2001/XMLSchema}string" /&amp;gt;
 * &amp;lt;attribute name="DIAGNOSTIC-CLASS" type="{}DIAG-CLASS-TYPE" /&amp;gt;
 * &amp;lt;attribute name="IS-MANDATORY" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&amp;gt;
 * &amp;lt;attribute name="IS-EXECUTABLE" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" /&amp;gt;
 * &amp;lt;attribute name="IS-FINAL" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&amp;gt;
 * &amp;lt;/restriction&amp;gt;
 * &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DIAG-COMM")
@XmlSeeAlso({
        DIAGSERVICE.class,
        SINGLEECUJOB.class
})
public abstract class DIAGCOMM extends AbstractLinkTarget implements LayerAware {

    @XmlElement(name = "SHORT-NAME", required = true)
    protected String shortname;
    @XmlElement(name = "LONG-NAME")
    protected LONGNAME longname;
    @XmlElement(name = "DESC")
    protected DESCRIPTION desc;
    @XmlElement(name = "ADMIN-DATA")
    protected ADMINDATA admindata;
    @XmlElement(name = "SDGS")
    protected SDGS sdgs;
    @XmlElement(name = "FUNCT-CLASS-REFS")
    protected FUNCTCLASSREFS functclassrefs;
    @XmlElement(name = "AUDIENCE")
    protected AUDIENCE audience;
    @XmlElement(name = "PROTOCOL-SNREFS")
    protected PROTOCOLSNREFS protocolsnrefs;
    @XmlElement(name = "PRE-CONDITION-STATE-REFS")
    protected PRECONDITIONSTATEREFS preconditionstaterefs;
    @XmlElement(name = "STATE-TRANSITION-REFS")
    protected STATETRANSITIONREFS statetransitionrefs;
    @XmlAttribute(name = "ID", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "OID")
    @XmlTransient
    protected String oid;
    @XmlAttribute(name = "SEMANTIC")
    protected String semantic;
    @XmlAttribute(name = "DIAGNOSTIC-CLASS")
    protected DIAGCLASSTYPE diagnosticclass;
    @XmlAttribute(name = "IS-MANDATORY")
    protected Boolean ismandatory;
    @XmlAttribute(name = "IS-EXECUTABLE")
    protected Boolean isexecutable;
    @XmlAttribute(name = "IS-FINAL")
    protected Boolean isfinal;
    @XmlPath("RELATED-DIAG-COMM-REFS/RELATED-DIAG-COMM-REF")
    protected List<RELATEDDIAGCOMMREF> relateddiagcommrefs = new ArrayList<>();
    @XmlTransient
    private Layer layer;

    /**
     * Gets the value of the shortname property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSHORTNAME() {
        return shortname;
    }

    /**
     * Sets the value of the shortname property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSHORTNAME(final String value) {
        this.shortname = value;
    }

    /**
     * Gets the value of the longname property.
     *
     * @return possible object is
     * {@link LONGNAME }
     */
    public LONGNAME getLONGNAME() {
        return longname;
    }

    /**
     * Sets the value of the longname property.
     *
     * @param value allowed object is
     *              {@link LONGNAME }
     */
    public void setLONGNAME(final LONGNAME value) {
        this.longname = value;
    }

    /**
     * Gets the value of the desc property.
     *
     * @return possible object is
     * {@link DESCRIPTION }
     */
    public DESCRIPTION getDESC() {
        return desc;
    }

    /**
     * Sets the value of the desc property.
     *
     * @param value allowed object is
     *              {@link DESCRIPTION }
     */
    public void setDESC(final DESCRIPTION value) {
        this.desc = value;
    }

    /**
     * Gets the value of the admindata property.
     *
     * @return possible object is
     * {@link ADMINDATA }
     */
    public ADMINDATA getADMINDATA() {
        return admindata;
    }

    /**
     * Sets the value of the admindata property.
     *
     * @param value allowed object is
     *              {@link ADMINDATA }
     */
    public void setADMINDATA(final ADMINDATA value) {
        this.admindata = value;
    }

    /**
     * Gets the value of the sdgs property.
     *
     * @return possible object is
     * {@link SDGS }
     */
    public SDGS getSDGS() {
        return sdgs;
    }

    /**
     * Sets the value of the sdgs property.
     *
     * @param value allowed object is
     *              {@link SDGS }
     */
    public void setSDGS(final SDGS value) {
        this.sdgs = value;
    }

    /**
     * Gets the value of the functclassrefs property.
     *
     * @return possible object is
     * {@link FUNCTCLASSREFS }
     */
    public FUNCTCLASSREFS getFUNCTCLASSREFS() {
        return functclassrefs;
    }

    /**
     * Sets the value of the functclassrefs property.
     *
     * @param value allowed object is
     *              {@link FUNCTCLASSREFS }
     */
    public void setFUNCTCLASSREFS(final FUNCTCLASSREFS value) {
        this.functclassrefs = value;
    }

    /**
     * Gets the value of the audience property.
     *
     * @return possible object is
     * {@link AUDIENCE }
     */
    public AUDIENCE getAUDIENCE() {
        return audience;
    }

    /**
     * Sets the value of the audience property.
     *
     * @param value allowed object is
     *              {@link AUDIENCE }
     */
    public void setAUDIENCE(final AUDIENCE value) {
        this.audience = value;
    }

    /**
     * Gets the value of the protocolsnrefs property.
     *
     * @return possible object is
     * {@link PROTOCOLSNREFS }
     */
    public PROTOCOLSNREFS getPROTOCOLSNREFS() {
        return protocolsnrefs;
    }

    /**
     * Sets the value of the protocolsnrefs property.
     *
     * @param value allowed object is
     *              {@link PROTOCOLSNREFS }
     */
    public void setPROTOCOLSNREFS(final PROTOCOLSNREFS value) {
        this.protocolsnrefs = value;
    }


    /**
     * Gets the value of the preconditionstaterefs property.
     *
     * @return possible object is
     * {@link PRECONDITIONSTATEREFS }
     */
    public PRECONDITIONSTATEREFS getPRECONDITIONSTATEREFS() {
        return preconditionstaterefs;
    }

    /**
     * Sets the value of the preconditionstaterefs property.
     *
     * @param value allowed object is
     *              {@link PRECONDITIONSTATEREFS }
     */
    public void setPRECONDITIONSTATEREFS(final PRECONDITIONSTATEREFS value) {
        this.preconditionstaterefs = value;
    }

    /**
     * Gets the value of the statetransitionrefs property.
     *
     * @return possible object is
     * {@link STATETRANSITIONREFS }
     */
    public STATETRANSITIONREFS getSTATETRANSITIONREFS() {
        return statetransitionrefs;
    }

    /**
     * Sets the value of the statetransitionrefs property.
     *
     * @param value allowed object is
     *              {@link STATETRANSITIONREFS }
     */
    public void setSTATETRANSITIONREFS(final STATETRANSITIONREFS value) {
        this.statetransitionrefs = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setID(final String value) {
        this.id = value;
    }

    /**
     * Gets the value of the oid property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getOID() {
        return oid;
    }

    /**
     * Sets the value of the oid property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setOID(final String value) {
        this.oid = value;
    }

    /**
     * Gets the value of the semantic property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSEMANTIC() {
        return semantic;
    }

    /**
     * Sets the value of the semantic property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSEMANTIC(final String value) {
        this.semantic = value;
    }

    /**
     * Gets the value of the diagnosticclass property.
     *
     * @return possible object is
     * {@link DIAGCLASSTYPE }
     */
    public DIAGCLASSTYPE getDIAGNOSTICCLASS() {
        return diagnosticclass;
    }

    /**
     * Sets the value of the diagnosticclass property.
     *
     * @param value allowed object is
     *              {@link DIAGCLASSTYPE }
     */
    public void setDIAGNOSTICCLASS(final DIAGCLASSTYPE value) {
        this.diagnosticclass = value;
    }

    /**
     * Gets the value of the ismandatory property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public boolean isISMANDATORY() {
        if (ismandatory == null) {
            return false;
        } else {
            return ismandatory;
        }
    }

    /**
     * Sets the value of the ismandatory property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setISMANDATORY(final Boolean value) {
        this.ismandatory = value;
    }

    /**
     * Gets the value of the isexecutable property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public boolean isISEXECUTABLE() {
        if (isexecutable == null) {
            return true;
        } else {
            return isexecutable;
        }
    }

    /**
     * Sets the value of the isexecutable property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setISEXECUTABLE(final Boolean value) {
        this.isexecutable = value;
    }

    /**
     * Gets the value of the isfinal property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public boolean isISFINAL() {
        if (isfinal == null) {
            return false;
        } else {
            return isfinal;
        }
    }

    /**
     * Sets the value of the isfinal property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setISFINAL(final Boolean value) {
        this.isfinal = value;
    }

    @Override
    public Layer getLayer() {
        return layer;
    }

    @Override
    public void setLayer(final Layer layer) {
        this.layer = layer;
    }

    public List<RELATEDDIAGCOMMREF> getRelateddiagcommrefs() {
        return relateddiagcommrefs;
    }
}
