//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.28 at 09:58:19 AM CET 
//


package com.javahacks.odx.model;

import org.eclipse.persistence.oxm.annotations.XmlPath;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * &lt;p&gt;Java class for DIAG-LAYER-CONTAINER complex type.
 * <p>
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * <p>
 * &lt;pre&gt;
 * &amp;lt;complexType name="DIAG-LAYER-CONTAINER"&amp;gt;
 * &amp;lt;complexContent&amp;gt;
 * &amp;lt;extension base="{}ODX-CATEGORY"&amp;gt;
 * &amp;lt;sequence&amp;gt;
 * &amp;lt;element name="PROTOCOLS" type="{}PROTOCOLS" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="FUNCTIONAL-GROUPS" type="{}FUNCTIONAL-GROUPS" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="ECU-SHARED-DATAS" type="{}ECU-SHARED-DATAS" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="BASE-VARIANTS" type="{}BASE-VARIANTS" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="ECU-VARIANTS" type="{}ECU-VARIANTS" minOccurs="0"/&amp;gt;
 * &amp;lt;/sequence&amp;gt;
 * &amp;lt;/extension&amp;gt;
 * &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DIAG-LAYER-CONTAINER")
public class DIAGLAYERCONTAINER extends ODXCATEGORY {

    @XmlPath("PROTOCOLS/PROTOCOL")
    private final List<PROTOCOL> protocols = new ArrayList<>();

    @XmlPath("FUNCTIONAL-GROUPS/FUNCTIONAL-GROUP")
    private final List<FUNCTIONALGROUP> functionalGroups = new ArrayList<>();

    @XmlPath("ECU-SHARED-DATAS/ECU-SHARED-DATA")
    private final List<ECUSHAREDDATA> ecusharedDatas = new ArrayList<>();

    @XmlPath("BASE-VARIANTS/BASE-VARIANT")
    private final List<BASEVARIANT> baseVariants = new ArrayList<>();

    @XmlPath("ECU-VARIANTS/ECU-VARIANT")
    private final List<ECUVARIANT> ecuVariants = new ArrayList<>();

    public List<PROTOCOL> getProtocols() {
        return protocols;
    }

    public List<FUNCTIONALGROUP> getFunctionalGroups() {
        return functionalGroups;
    }

    public List<ECUSHAREDDATA> getEcusharedDatas() {
        return ecusharedDatas;
    }

    public List<BASEVARIANT> getBaseVariants() {
        return baseVariants;
    }

    public List<ECUVARIANT> getEcuVariants() {
        return ecuVariants;
    }
}
