//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.28 at 09:58:19 AM CET 
//


package com.javahacks.odx.model;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * &lt;p&gt;Java class for DIAG-VARIABLE complex type.
 * <p>
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * <p>
 * &lt;pre&gt;
 * &amp;lt;complexType name="DIAG-VARIABLE"&amp;gt;
 * &amp;lt;complexContent&amp;gt;
 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 * &amp;lt;sequence&amp;gt;
 * &amp;lt;group ref="{}ELEMENT-ID"/&amp;gt;
 * &amp;lt;element name="ADMIN-DATA" type="{}ADMIN-DATA" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="VARIABLE-GROUP-REF" type="{}ODXLINK" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="SW-VARIABLES" type="{}SW-VARIABLES" minOccurs="0"/&amp;gt;
 * &amp;lt;choice&amp;gt;
 * &amp;lt;element name="COMM-RELATIONS" type="{}COMM-RELATIONS" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="SNREF-TO-TABLEROW" type="{}SNREF-TO-TABLEROW" minOccurs="0"/&amp;gt;
 * &amp;lt;/choice&amp;gt;
 * &amp;lt;element name="SDGS" type="{}SDGS" minOccurs="0"/&amp;gt;
 * &amp;lt;/sequence&amp;gt;
 * &amp;lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" /&amp;gt;
 * &amp;lt;attribute name="OID" type="{http://www.w3.org/2001/XMLSchema}string" /&amp;gt;
 * &amp;lt;attribute name="IS-READ-BEFORE-WRITE" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&amp;gt;
 * &amp;lt;/restriction&amp;gt;
 * &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DIAG-VARIABLE")
public class DIAGVARIABLE {

    @XmlElement(name = "SHORT-NAME", required = true)
    protected String shortname;
    @XmlElement(name = "LONG-NAME")
    protected LONGNAME longname;
    @XmlElement(name = "DESC")
    protected DESCRIPTION desc;
    @XmlElement(name = "ADMIN-DATA")
    protected ADMINDATA admindata;
    @XmlElement(name = "VARIABLE-GROUP-REF")
    protected ODXLINK variablegroupref;
    @XmlElement(name = "SW-VARIABLES")
    protected SWVARIABLES swvariables;
    @XmlElement(name = "COMM-RELATIONS")
    protected COMMRELATIONS commrelations;
    @XmlElement(name = "SNREF-TO-TABLEROW")
    protected SNREFTOTABLEROW snreftotablerow;
    @XmlElement(name = "SDGS")
    protected SDGS sdgs;
    @XmlAttribute(name = "ID", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "OID")
    @XmlTransient
    protected String oid;
    @XmlAttribute(name = "IS-READ-BEFORE-WRITE")
    protected Boolean isreadbeforewrite;

    /**
     * Gets the value of the shortname property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSHORTNAME() {
        return shortname;
    }

    /**
     * Sets the value of the shortname property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSHORTNAME(final String value) {
        this.shortname = value;
    }

    /**
     * Gets the value of the longname property.
     *
     * @return possible object is
     * {@link LONGNAME }
     */
    public LONGNAME getLONGNAME() {
        return longname;
    }

    /**
     * Sets the value of the longname property.
     *
     * @param value allowed object is
     *              {@link LONGNAME }
     */
    public void setLONGNAME(final LONGNAME value) {
        this.longname = value;
    }

    /**
     * Gets the value of the desc property.
     *
     * @return possible object is
     * {@link DESCRIPTION }
     */
    public DESCRIPTION getDESC() {
        return desc;
    }

    /**
     * Sets the value of the desc property.
     *
     * @param value allowed object is
     *              {@link DESCRIPTION }
     */
    public void setDESC(final DESCRIPTION value) {
        this.desc = value;
    }

    /**
     * Gets the value of the admindata property.
     *
     * @return possible object is
     * {@link ADMINDATA }
     */
    public ADMINDATA getADMINDATA() {
        return admindata;
    }

    /**
     * Sets the value of the admindata property.
     *
     * @param value allowed object is
     *              {@link ADMINDATA }
     */
    public void setADMINDATA(final ADMINDATA value) {
        this.admindata = value;
    }

    /**
     * Gets the value of the variablegroupref property.
     *
     * @return possible object is
     * {@link ODXLINK }
     */
    public ODXLINK getVARIABLEGROUPREF() {
        return variablegroupref;
    }

    /**
     * Sets the value of the variablegroupref property.
     *
     * @param value allowed object is
     *              {@link ODXLINK }
     */
    public void setVARIABLEGROUPREF(final ODXLINK value) {
        this.variablegroupref = value;
    }

    /**
     * Gets the value of the swvariables property.
     *
     * @return possible object is
     * {@link SWVARIABLES }
     */
    public SWVARIABLES getSWVARIABLES() {
        return swvariables;
    }

    /**
     * Sets the value of the swvariables property.
     *
     * @param value allowed object is
     *              {@link SWVARIABLES }
     */
    public void setSWVARIABLES(final SWVARIABLES value) {
        this.swvariables = value;
    }

    /**
     * Gets the value of the commrelations property.
     *
     * @return possible object is
     * {@link COMMRELATIONS }
     */
    public COMMRELATIONS getCOMMRELATIONS() {
        return commrelations;
    }

    /**
     * Sets the value of the commrelations property.
     *
     * @param value allowed object is
     *              {@link COMMRELATIONS }
     */
    public void setCOMMRELATIONS(final COMMRELATIONS value) {
        this.commrelations = value;
    }

    /**
     * Gets the value of the snreftotablerow property.
     *
     * @return possible object is
     * {@link SNREFTOTABLEROW }
     */
    public SNREFTOTABLEROW getSNREFTOTABLEROW() {
        return snreftotablerow;
    }

    /**
     * Sets the value of the snreftotablerow property.
     *
     * @param value allowed object is
     *              {@link SNREFTOTABLEROW }
     */
    public void setSNREFTOTABLEROW(final SNREFTOTABLEROW value) {
        this.snreftotablerow = value;
    }

    /**
     * Gets the value of the sdgs property.
     *
     * @return possible object is
     * {@link SDGS }
     */
    public SDGS getSDGS() {
        return sdgs;
    }

    /**
     * Sets the value of the sdgs property.
     *
     * @param value allowed object is
     *              {@link SDGS }
     */
    public void setSDGS(final SDGS value) {
        this.sdgs = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setID(final String value) {
        this.id = value;
    }

    /**
     * Gets the value of the oid property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getOID() {
        return oid;
    }

    /**
     * Sets the value of the oid property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setOID(final String value) {
        this.oid = value;
    }

    /**
     * Gets the value of the isreadbeforewrite property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public boolean isISREADBEFOREWRITE() {
        if (isreadbeforewrite == null) {
            return false;
        } else {
            return isreadbeforewrite;
        }
    }

    /**
     * Sets the value of the isreadbeforewrite property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setISREADBEFOREWRITE(final Boolean value) {
        this.isreadbeforewrite = value;
    }

}
