//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.28 at 09:58:19 AM CET 
//


package com.javahacks.odx.model;

import org.eclipse.persistence.oxm.annotations.XmlPath;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * &lt;p&gt;Java class for DIAG-DATA-DICTIONARY-SPEC complex type.
 * <p>
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * <p>
 * &lt;pre&gt;
 * &amp;lt;complexType name="DIAG-DATA-DICTIONARY-SPEC"&amp;gt;
 * &amp;lt;complexContent&amp;gt;
 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 * &amp;lt;sequence&amp;gt;
 * &amp;lt;element name="ADMIN-DATA" type="{}ADMIN-DATA" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="DTC-DOPS" type="{}DTC-DOPS" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="ENV-DATA-DESCS" type="{}ENV-DATA-DESCS" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="DATA-OBJECT-PROPS" type="{}DATA-OBJECT-PROPS" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="STRUCTURES" type="{}STRUCTURES" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="STATIC-FIELDS" type="{}STATIC-FIELDS" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="DYNAMIC-LENGTH-FIELDS" type="{}DYNAMIC-LENGTH-FIELDS" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="DYNAMIC-ENDMARKER-FIELDS" type="{}DYNAMIC-ENDMARKER-FIELDS" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="END-OF-PDU-FIELDS" type="{}END-OF-PDU-FIELDS" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="MUXS" type="{}MUXS" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="ENV-DATAS" type="{}ENV-DATAS" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="UNIT-SPEC" type="{}UNIT-SPEC" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="TABLES" type="{}TABLES" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="SDGS" type="{}SDGS" minOccurs="0"/&amp;gt;
 * &amp;lt;/sequence&amp;gt;
 * &amp;lt;/restriction&amp;gt;
 * &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DIAG-DATA-DICTIONARY-SPEC")
public class DIAGDATADICTIONARYSPEC {

    @XmlElement(name = "ADMIN-DATA")
    protected ADMINDATA admindata;

    @XmlElement(name = "UNIT-SPEC")
    protected UNITSPEC unitspec;

    @XmlElement(name = "SDGS")
    protected SDGS sdgs;

    @XmlPath("TABLES/TABLE")
    protected List<TABLE> tables = new ArrayList<>();

    @XmlPath("DTC-DOPS/DTC-DOP")
    protected List<DTCDOP> dtcdops = new ArrayList<>();

    @XmlPath("ENV-DATA-DESCS/ENV-DATA-DESC")
    protected List<ENVDATADESC> envdatadescs = new ArrayList<>();

    @XmlPath("ENV-DATAS/ENV-DATA")
    protected List<ENVDATA> envdatas = new ArrayList<>();

    @XmlPath("END-OF-PDU-FIELDS/END-OF-PDU-FIELD")
    protected List<ENDOFPDUFIELD> endofpdufields = new ArrayList<>();

    @XmlPath("DYNAMIC-LENGTH-FIELDS/DYNAMIC-LENGTH-FIELD")
    protected List<DYNAMICLENGTHFIELD> dynamiclengthfields = new ArrayList<>();
    @XmlPath("DYNAMIC-ENDMARKER-FIELDS/DYNAMIC-ENDMARKER-FIELD")
    protected List<DYNAMICENDMARKERFIELD> dynamicendmarkerfields = new ArrayList<>();
    @XmlPath("DATA-OBJECT-PROPS/DATA-OBJECT-PROP")
    protected List<DATAOBJECTPROP> dataobjectprops = new ArrayList<>();
    @XmlPath("STRUCTURES/STRUCTURE")
    protected List<STRUCTURE> structures = new ArrayList<>();
    @XmlPath("STATIC-FIELDS/STATIC-FIELD")
    protected List<STATICFIELD> staticfields = new ArrayList<>();
    @XmlPath("MUXS/MUX")
    protected List<MUX> muxs = new ArrayList<>();

    /**
     * Gets the value of the admindata property.
     *
     * @return possible object is
     * {@link ADMINDATA }
     */
    public ADMINDATA getADMINDATA() {
        return admindata;
    }

    /**
     * Sets the value of the admindata property.
     *
     * @param value allowed object is
     *              {@link ADMINDATA }
     */
    public void setADMINDATA(final ADMINDATA value) {
        this.admindata = value;
    }


    /**
     * Gets the value of the unitspec property.
     *
     * @return possible object is
     * {@link UNITSPEC }
     */
    public UNITSPEC getUNITSPEC() {
        return unitspec;
    }

    /**
     * Sets the value of the unitspec property.
     *
     * @param value allowed object is
     *              {@link UNITSPEC }
     */
    public void setUNITSPEC(final UNITSPEC value) {
        this.unitspec = value;
    }


    /**
     * Gets the value of the sdgs property.
     *
     * @return possible object is
     * {@link SDGS }
     */
    public SDGS getSDGS() {
        return sdgs;
    }

    /**
     * Sets the value of the sdgs property.
     *
     * @param value allowed object is
     *              {@link SDGS }
     */
    public void setSDGS(final SDGS value) {
        this.sdgs = value;
    }

    public List<DATAOBJECTPROP> getDataobjectprops() {
        return dataobjectprops;
    }

    public List<MUX> getMuxs() {
        return muxs;
    }

    public List<STATICFIELD> getStaticfields() {
        return staticfields;
    }

    public List<STRUCTURE> getStructures() {
        return structures;
    }

    public List<ENDOFPDUFIELD> getEndofpdufields() {
        return endofpdufields;
    }

    public List<DTCDOP> getDtcdops() {
        return dtcdops;
    }

    public List<ENVDATA> getEnvdatas() {
        return envdatas;
    }

    public List<ENVDATADESC> getEnvdatadescs() {
        return envdatadescs;
    }

    public List<DYNAMICENDMARKERFIELD> getDynamicendmarkerfields() {
        return dynamicendmarkerfields;
    }

    public List<DYNAMICLENGTHFIELD> getDynamiclengthfields() {
        return dynamiclengthfields;
    }

    public List<TABLE> getTables() {
        return tables;
    }

}
