//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.28 at 09:58:19 AM CET 
//


package com.javahacks.odx.model;

import javax.xml.bind.annotation.*;


/**
 * &lt;p&gt;Java class for DIAG-CODED-TYPE complex type.
 * <p>
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * <p>
 * &lt;pre&gt;
 * &amp;lt;complexType name="DIAG-CODED-TYPE"&amp;gt;
 * &amp;lt;complexContent&amp;gt;
 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 * &amp;lt;attribute name="BASE-TYPE-ENCODING" type="{}ENCODING" /&amp;gt;
 * &amp;lt;attribute name="BASE-DATA-TYPE" use="required" type="{}DATA-TYPE" /&amp;gt;
 * &amp;lt;attribute name="IS-HIGHLOW-BYTE-ORDER" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" /&amp;gt;
 * &amp;lt;/restriction&amp;gt;
 * &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DIAG-CODED-TYPE")
@XmlSeeAlso({
        LEADINGLENGTHINFOTYPE.class,
        MINMAXLENGTHTYPE.class,
        PARAMLENGTHINFOTYPE.class,
        STANDARDLENGTHTYPE.class
})
public abstract class DIAGCODEDTYPE {

    @XmlAttribute(name = "BASE-TYPE-ENCODING")
    protected String basetypeencoding;
    @XmlAttribute(name = "BASE-DATA-TYPE", required = true)
    protected DATATYPE basedatatype;
    @XmlAttribute(name = "IS-HIGHLOW-BYTE-ORDER")
    protected Boolean ishighlowbyteorder;

    /**
     * Gets the value of the basetypeencoding property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getBASETYPEENCODING() {
        return basetypeencoding;
    }

    /**
     * Sets the value of the basetypeencoding property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setBASETYPEENCODING(String value) {
        this.basetypeencoding = value;
    }

    /**
     * Gets the value of the basedatatype property.
     *
     * @return possible object is
     * {@link DATATYPE }
     */
    public DATATYPE getBASEDATATYPE() {
        return basedatatype;
    }

    /**
     * Sets the value of the basedatatype property.
     *
     * @param value allowed object is
     *              {@link DATATYPE }
     */
    public void setBASEDATATYPE(DATATYPE value) {
        this.basedatatype = value;
    }

    /**
     * Gets the value of the ishighlowbyteorder property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public boolean isISHIGHLOWBYTEORDER() {
        if (ishighlowbyteorder == null) {
            return true;
        } else {
            return ishighlowbyteorder;
        }
    }

    /**
     * Sets the value of the ishighlowbyteorder property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setISHIGHLOWBYTEORDER(Boolean value) {
        this.ishighlowbyteorder = value;
    }

}
