//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.28 at 09:58:19 AM CET 
//


package com.javahacks.odx.model;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * &lt;p&gt;Java class for DOC-REVISION complex type.
 * <p>
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * <p>
 * &lt;pre&gt;
 * &amp;lt;complexType name="DOC-REVISION"&amp;gt;
 * &amp;lt;complexContent&amp;gt;
 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 * &amp;lt;sequence&amp;gt;
 * &amp;lt;element name="TEAM-MEMBER-REF" type="{}ODXLINK" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="REVISION-LABEL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="STATE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="DATE" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&amp;gt;
 * &amp;lt;element name="TOOL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="COMPANY-REVISION-INFOS" type="{}COMPANY-REVISION-INFOS" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="MODIFICATIONS" type="{}MODIFICATIONS" minOccurs="0"/&amp;gt;
 * &amp;lt;/sequence&amp;gt;
 * &amp;lt;/restriction&amp;gt;
 * &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DOC-REVISION")
public class DOCREVISION {

    @XmlElement(name = "TEAM-MEMBER-REF")
    protected ODXLINK teammemberref;
    @XmlElement(name = "REVISION-LABEL")
    protected String revisionlabel;
    @XmlElement(name = "STATE")
    protected String state;
    @XmlElement(name = "DATE", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar date;
    @XmlElement(name = "TOOL")
    protected String tool;
    @XmlElement(name = "COMPANY-REVISION-INFOS")
    protected COMPANYREVISIONINFOS companyrevisioninfos;
    @XmlElement(name = "MODIFICATIONS")
    protected MODIFICATIONS modifications;

    /**
     * Gets the value of the teammemberref property.
     *
     * @return possible object is
     * {@link ODXLINK }
     */
    public ODXLINK getTEAMMEMBERREF() {
        return teammemberref;
    }

    /**
     * Sets the value of the teammemberref property.
     *
     * @param value allowed object is
     *              {@link ODXLINK }
     */
    public void setTEAMMEMBERREF(ODXLINK value) {
        this.teammemberref = value;
    }

    /**
     * Gets the value of the revisionlabel property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getREVISIONLABEL() {
        return revisionlabel;
    }

    /**
     * Sets the value of the revisionlabel property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setREVISIONLABEL(String value) {
        this.revisionlabel = value;
    }

    /**
     * Gets the value of the state property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSTATE() {
        return state;
    }

    /**
     * Sets the value of the state property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSTATE(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the date property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getDATE() {
        return date;
    }

    /**
     * Sets the value of the date property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setDATE(XMLGregorianCalendar value) {
        this.date = value;
    }

    /**
     * Gets the value of the tool property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getTOOL() {
        return tool;
    }

    /**
     * Sets the value of the tool property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setTOOL(String value) {
        this.tool = value;
    }

    /**
     * Gets the value of the companyrevisioninfos property.
     *
     * @return possible object is
     * {@link COMPANYREVISIONINFOS }
     */
    public COMPANYREVISIONINFOS getCOMPANYREVISIONINFOS() {
        return companyrevisioninfos;
    }

    /**
     * Sets the value of the companyrevisioninfos property.
     *
     * @param value allowed object is
     *              {@link COMPANYREVISIONINFOS }
     */
    public void setCOMPANYREVISIONINFOS(COMPANYREVISIONINFOS value) {
        this.companyrevisioninfos = value;
    }

    /**
     * Gets the value of the modifications property.
     *
     * @return possible object is
     * {@link MODIFICATIONS }
     */
    public MODIFICATIONS getMODIFICATIONS() {
        return modifications;
    }

    /**
     * Sets the value of the modifications property.
     *
     * @param value allowed object is
     *              {@link MODIFICATIONS }
     */
    public void setMODIFICATIONS(MODIFICATIONS value) {
        this.modifications = value;
    }

}
