//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.28 at 09:58:19 AM CET 
//


package com.javahacks.odx.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for DOCTYPE.
 * <p>
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * &lt;pre&gt;
 * &amp;lt;simpleType name="DOCTYPE"&amp;gt;
 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt;
 * &amp;lt;enumeration value="FLASH"/&amp;gt;
 * &amp;lt;enumeration value="CONTAINER"/&amp;gt;
 * &amp;lt;enumeration value="LAYER"/&amp;gt;
 * &amp;lt;enumeration value="MULTIPLE-ECU-JOB-SPEC"/&amp;gt;
 * &amp;lt;enumeration value="COMPARAM-SPEC"/&amp;gt;
 * &amp;lt;enumeration value="VEHICLE-INFO-SPEC"/&amp;gt;
 * &amp;lt;enumeration value="COMPARAM-SUBSET"/&amp;gt;
 * &amp;lt;enumeration value="ECU-CONFIG"/&amp;gt;
 * &amp;lt;enumeration value="FUNCTION-DICTIONARY-SPEC"/&amp;gt;
 * &amp;lt;/restriction&amp;gt;
 * &amp;lt;/simpleType&amp;gt;
 * &lt;/pre&gt;
 */
@XmlType(name = "DOCTYPE")
@XmlEnum
public enum DOCTYPE {

    FLASH("FLASH"),
    CONTAINER("CONTAINER"),
    LAYER("LAYER"),
    @XmlEnumValue("MULTIPLE-ECU-JOB-SPEC")
    MULTIPLE_ECU_JOB_SPEC("MULTIPLE-ECU-JOB-SPEC"),
    @XmlEnumValue("COMPARAM-SPEC")
    COMPARAM_SPEC("COMPARAM-SPEC"),
    @XmlEnumValue("VEHICLE-INFO-SPEC")
    VEHICLE_INFO_SPEC("VEHICLE-INFO-SPEC"),
    @XmlEnumValue("COMPARAM-SUBSET")
    COMPARAM_SUBSET("COMPARAM-SUBSET"),
    @XmlEnumValue("ECU-CONFIG")
    ECU_CONFIG("ECU-CONFIG"),
    @XmlEnumValue("FUNCTION-DICTIONARY-SPEC")
    FUNCTION_DICTIONARY_SPEC("FUNCTION-DICTIONARY-SPEC");
    private final String value;

    DOCTYPE(String v) {
        value = v;
    }

    public static DOCTYPE fromValue(String v) {
        for (DOCTYPE c : DOCTYPE.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

    public String value() {
        return value;
    }

}
