//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.28 at 09:58:19 AM CET 
//


package com.javahacks.odx.model;

import com.javahacks.odx.index.AbstractLinkTarget;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * &lt;p&gt;Java class for DTC complex type.
 * <p>
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * <p>
 * &lt;pre&gt;
 * &amp;lt;complexType name="DTC"&amp;gt;
 * &amp;lt;complexContent&amp;gt;
 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 * &amp;lt;sequence&amp;gt;
 * &amp;lt;element name="SHORT-NAME"&amp;gt;
 * &amp;lt;simpleType&amp;gt;
 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt;
 * &amp;lt;pattern value="[a-zA-Z0-9_]{1,128}"/&amp;gt;
 * &amp;lt;/restriction&amp;gt;
 * &amp;lt;/simpleType&amp;gt;
 * &amp;lt;/element&amp;gt;
 * &amp;lt;element name="TROUBLE-CODE" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/&amp;gt;
 * &amp;lt;element name="DISPLAY-TROUBLE-CODE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="TEXT" type="{}TEXT"/&amp;gt;
 * &amp;lt;element name="LEVEL" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="SDGS" type="{}SDGS" minOccurs="0"/&amp;gt;
 * &amp;lt;/sequence&amp;gt;
 * &amp;lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" /&amp;gt;
 * &amp;lt;attribute name="OID" type="{http://www.w3.org/2001/XMLSchema}string" /&amp;gt;
 * &amp;lt;attribute name="IS-TEMPORARY" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&amp;gt;
 * &amp;lt;/restriction&amp;gt;
 * &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DTC")
public class DTC extends AbstractLinkTarget {

    @XmlElement(name = "SHORT-NAME", required = true)
    protected String shortname;
    @XmlElement(name = "TROUBLE-CODE")
    @XmlSchemaType(name = "unsignedInt")
    protected long troublecode;
    @XmlElement(name = "DISPLAY-TROUBLE-CODE")
    protected String displaytroublecode;
    @XmlElement(name = "TEXT", required = true)
    protected TEXT text;
    @XmlElement(name = "LEVEL")
    @XmlSchemaType(name = "unsignedByte")
    protected Short level;
    @XmlElement(name = "SDGS")
    protected SDGS sdgs;
    @XmlAttribute(name = "ID", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "OID")
    @XmlTransient
    protected String oid;
    @XmlAttribute(name = "IS-TEMPORARY")
    protected Boolean istemporary;

    /**
     * Gets the value of the shortname property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSHORTNAME() {
        return shortname;
    }

    /**
     * Sets the value of the shortname property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSHORTNAME(final String value) {
        this.shortname = value;
    }

    /**
     * Gets the value of the troublecode property.
     */
    public long getTROUBLECODE() {
        return troublecode;
    }

    /**
     * Sets the value of the troublecode property.
     */
    public void setTROUBLECODE(final long value) {
        this.troublecode = value;
    }

    /**
     * Gets the value of the displaytroublecode property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDISPLAYTROUBLECODE() {
        return displaytroublecode;
    }

    /**
     * Sets the value of the displaytroublecode property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDISPLAYTROUBLECODE(final String value) {
        this.displaytroublecode = value;
    }

    /**
     * Gets the value of the text property.
     *
     * @return possible object is
     * {@link TEXT }
     */
    public TEXT getTEXT() {
        return text;
    }

    /**
     * Sets the value of the text property.
     *
     * @param value allowed object is
     *              {@link TEXT }
     */
    public void setTEXT(final TEXT value) {
        this.text = value;
    }

    /**
     * Gets the value of the level property.
     *
     * @return possible object is
     * {@link Short }
     */
    public Short getLEVEL() {
        return level;
    }

    /**
     * Sets the value of the level property.
     *
     * @param value allowed object is
     *              {@link Short }
     */
    public void setLEVEL(final Short value) {
        this.level = value;
    }

    /**
     * Gets the value of the sdgs property.
     *
     * @return possible object is
     * {@link SDGS }
     */
    public SDGS getSDGS() {
        return sdgs;
    }

    /**
     * Sets the value of the sdgs property.
     *
     * @param value allowed object is
     *              {@link SDGS }
     */
    public void setSDGS(final SDGS value) {
        this.sdgs = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setID(final String value) {
        this.id = value;
    }

    /**
     * Gets the value of the oid property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getOID() {
        return oid;
    }

    /**
     * Sets the value of the oid property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setOID(final String value) {
        this.oid = value;
    }

    /**
     * Gets the value of the istemporary property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public boolean isISTEMPORARY() {
        if (istemporary == null) {
            return false;
        } else {
            return istemporary;
        }
    }

    /**
     * Sets the value of the istemporary property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setISTEMPORARY(final Boolean value) {
        this.istemporary = value;
    }

}
