//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.28 at 09:58:19 AM CET 
//


package com.javahacks.odx.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for DYNAMIC-ENDMARKER-FIELD complex type.
 * <p>
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * <p>
 * &lt;pre&gt;
 * &amp;lt;complexType name="DYNAMIC-ENDMARKER-FIELD"&amp;gt;
 * &amp;lt;complexContent&amp;gt;
 * &amp;lt;extension base="{}FIELD"&amp;gt;
 * &amp;lt;sequence&amp;gt;
 * &amp;lt;element name="DATA-OBJECT-PROP-REF" type="{}DYN-END-DOP-REF"/&amp;gt;
 * &amp;lt;/sequence&amp;gt;
 * &amp;lt;/extension&amp;gt;
 * &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DYNAMIC-ENDMARKER-FIELD")
public class DYNAMICENDMARKERFIELD
        extends FIELD {

    @XmlElement(name = "DATA-OBJECT-PROP-REF", required = true)
    protected DYNENDDOPREF dataobjectpropref;

    /**
     * Gets the value of the dataobjectpropref property.
     *
     * @return possible object is
     * {@link DYNENDDOPREF }
     */
    public DYNENDDOPREF getDATAOBJECTPROPREF() {
        return dataobjectpropref;
    }

    /**
     * Sets the value of the dataobjectpropref property.
     *
     * @param value allowed object is
     *              {@link DYNENDDOPREF }
     */
    public void setDATAOBJECTPROPREF(DYNENDDOPREF value) {
        this.dataobjectpropref = value;
    }

}
