//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.28 at 09:58:19 AM CET 
//


package com.javahacks.odx.model;

import javax.xml.bind.annotation.*;


/**
 * &lt;p&gt;Java class for DYN-END-DOP-REF complex type.
 * <p>
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * <p>
 * &lt;pre&gt;
 * &amp;lt;complexType name="DYN-END-DOP-REF"&amp;gt;
 * &amp;lt;complexContent&amp;gt;
 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 * &amp;lt;sequence&amp;gt;
 * &amp;lt;element name="TERMINATION-VALUE" type="{http://www.w3.org/2001/XMLSchema}string"/&amp;gt;
 * &amp;lt;/sequence&amp;gt;
 * &amp;lt;attGroup ref="{}ODXLINK-ATTR"/&amp;gt;
 * &amp;lt;/restriction&amp;gt;
 * &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DYN-END-DOP-REF")
public class DYNENDDOPREF {

    @XmlElement(name = "TERMINATION-VALUE", required = true)
    protected String terminationvalue;
    @XmlAttribute(name = "ID-REF", required = true)
    protected String idref;
    @XmlAttribute(name = "DOCREF")
    protected String docref;
    @XmlAttribute(name = "DOCTYPE")
    protected DOCTYPE doctype;
    @XmlAttribute(name = "REVISION")
    protected String revision;

    /**
     * Gets the value of the terminationvalue property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getTERMINATIONVALUE() {
        return terminationvalue;
    }

    /**
     * Sets the value of the terminationvalue property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setTERMINATIONVALUE(String value) {
        this.terminationvalue = value;
    }

    /**
     * Gets the value of the idref property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getIDREF() {
        return idref;
    }

    /**
     * Sets the value of the idref property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setIDREF(String value) {
        this.idref = value;
    }

    /**
     * Gets the value of the docref property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDOCREF() {
        return docref;
    }

    /**
     * Sets the value of the docref property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDOCREF(String value) {
        this.docref = value;
    }

    /**
     * Gets the value of the doctype property.
     *
     * @return possible object is
     * {@link DOCTYPE }
     */
    public DOCTYPE getDOCTYPE() {
        return doctype;
    }

    /**
     * Sets the value of the doctype property.
     *
     * @param value allowed object is
     *              {@link DOCTYPE }
     */
    public void setDOCTYPE(DOCTYPE value) {
        this.doctype = value;
    }

    /**
     * Gets the value of the revision property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getREVISION() {
        return revision;
    }

    /**
     * Sets the value of the revision property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setREVISION(String value) {
        this.revision = value;
    }

}
