//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.28 at 09:58:19 AM CET 
//


package com.javahacks.odx.model;

import com.javahacks.odx.index.AbstractLinkTarget;
import org.eclipse.persistence.oxm.annotations.XmlPath;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.List;


/**
 * &lt;p&gt;Java class for ECU-MEM-CONNECTOR complex type.
 * <p>
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * <p>
 * &lt;pre&gt;
 * &amp;lt;complexType name="ECU-MEM-CONNECTOR"&amp;gt;
 * &amp;lt;complexContent&amp;gt;
 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 * &amp;lt;sequence&amp;gt;
 * &amp;lt;group ref="{}ELEMENT-ID"/&amp;gt;
 * &amp;lt;element name="ADMIN-DATA" type="{}ADMIN-DATA" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="FLASH-CLASSS" type="{}FLASH-CLASSS" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="SESSION-DESCS" type="{}SESSION-DESCS" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="IDENT-DESCS" type="{}IDENT-DESCS" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="ECU-MEM-REF" type="{}ODXLINK"/&amp;gt;
 * &amp;lt;element name="LAYER-REFS" type="{}LAYER-REFS" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="ALL-VARIANT-REFS" type="{}ALL-VARIANT-REFS" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="SDGS" type="{}SDGS" minOccurs="0"/&amp;gt;
 * &amp;lt;/sequence&amp;gt;
 * &amp;lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" /&amp;gt;
 * &amp;lt;attribute name="OID" type="{http://www.w3.org/2001/XMLSchema}string" /&amp;gt;
 * &amp;lt;/restriction&amp;gt;
 * &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ECU-MEM-CONNECTOR")
public class ECUMEMCONNECTOR extends AbstractLinkTarget {

    @XmlElement(name = "SHORT-NAME", required = true)
    protected String shortname;
    @XmlElement(name = "LONG-NAME")
    protected LONGNAME longname;
    @XmlElement(name = "DESC")
    protected DESCRIPTION desc;
    @XmlElement(name = "ADMIN-DATA")
    protected ADMINDATA admindata;
    @XmlElement(name = "FLASH-CLASSS")
    protected FLASHCLASSS flashclasss;
    @XmlPath("SESSION-DESCS/SESSION-DESC")
    protected List<SESSIONDESC> sessiondescs;
    @XmlElement(name = "IDENT-DESCS")
    protected IDENTDESCS identdescs;
    @XmlElement(name = "ECU-MEM-REF", required = true)
    protected ODXLINK ecumemref;
    @XmlElement(name = "LAYER-REFS")
    protected LAYERREFS layerrefs;
    @XmlElement(name = "ALL-VARIANT-REFS")
    protected ALLVARIANTREFS allvariantrefs;
    @XmlElement(name = "SDGS")
    protected SDGS sdgs;
    @XmlAttribute(name = "ID", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "OID")
    @XmlTransient
    protected String oid;

    /**
     * Gets the value of the shortname property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSHORTNAME() {
        return shortname;
    }

    /**
     * Sets the value of the shortname property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSHORTNAME(final String value) {
        this.shortname = value;
    }

    /**
     * Gets the value of the longname property.
     *
     * @return possible object is
     * {@link LONGNAME }
     */
    public LONGNAME getLONGNAME() {
        return longname;
    }

    /**
     * Sets the value of the longname property.
     *
     * @param value allowed object is
     *              {@link LONGNAME }
     */
    public void setLONGNAME(final LONGNAME value) {
        this.longname = value;
    }

    /**
     * Gets the value of the desc property.
     *
     * @return possible object is
     * {@link DESCRIPTION }
     */
    public DESCRIPTION getDESC() {
        return desc;
    }

    /**
     * Sets the value of the desc property.
     *
     * @param value allowed object is
     *              {@link DESCRIPTION }
     */
    public void setDESC(final DESCRIPTION value) {
        this.desc = value;
    }

    /**
     * Gets the value of the admindata property.
     *
     * @return possible object is
     * {@link ADMINDATA }
     */
    public ADMINDATA getADMINDATA() {
        return admindata;
    }

    /**
     * Sets the value of the admindata property.
     *
     * @param value allowed object is
     *              {@link ADMINDATA }
     */
    public void setADMINDATA(final ADMINDATA value) {
        this.admindata = value;
    }

    /**
     * Gets the value of the flashclasss property.
     *
     * @return possible object is
     * {@link FLASHCLASSS }
     */
    public FLASHCLASSS getFLASHCLASSS() {
        return flashclasss;
    }

    /**
     * Sets the value of the flashclasss property.
     *
     * @param value allowed object is
     *              {@link FLASHCLASSS }
     */
    public void setFLASHCLASSS(final FLASHCLASSS value) {
        this.flashclasss = value;
    }

    public List<SESSIONDESC> getSESSIONDESCS() {
        return sessiondescs;
    }

    public void setSESSIONDESCS(final List<SESSIONDESC> value) {
        this.sessiondescs = value;
    }

    /**
     * Gets the value of the identdescs property.
     *
     * @return possible object is
     * {@link IDENTDESCS }
     */
    public IDENTDESCS getIDENTDESCS() {
        return identdescs;
    }

    /**
     * Sets the value of the identdescs property.
     *
     * @param value allowed object is
     *              {@link IDENTDESCS }
     */
    public void setIDENTDESCS(final IDENTDESCS value) {
        this.identdescs = value;
    }

    /**
     * Gets the value of the ecumemref property.
     *
     * @return possible object is
     * {@link ODXLINK }
     */
    public ODXLINK getECUMEMREF() {
        return ecumemref;
    }

    /**
     * Sets the value of the ecumemref property.
     *
     * @param value allowed object is
     *              {@link ODXLINK }
     */
    public void setECUMEMREF(final ODXLINK value) {
        this.ecumemref = value;
    }

    /**
     * Gets the value of the layerrefs property.
     *
     * @return possible object is
     * {@link LAYERREFS }
     */
    public LAYERREFS getLAYERREFS() {
        return layerrefs;
    }

    /**
     * Sets the value of the layerrefs property.
     *
     * @param value allowed object is
     *              {@link LAYERREFS }
     */
    public void setLAYERREFS(final LAYERREFS value) {
        this.layerrefs = value;
    }

    /**
     * Gets the value of the allvariantrefs property.
     *
     * @return possible object is
     * {@link ALLVARIANTREFS }
     */
    public ALLVARIANTREFS getALLVARIANTREFS() {
        return allvariantrefs;
    }

    /**
     * Sets the value of the allvariantrefs property.
     *
     * @param value allowed object is
     *              {@link ALLVARIANTREFS }
     */
    public void setALLVARIANTREFS(final ALLVARIANTREFS value) {
        this.allvariantrefs = value;
    }

    /**
     * Gets the value of the sdgs property.
     *
     * @return possible object is
     * {@link SDGS }
     */
    public SDGS getSDGS() {
        return sdgs;
    }

    /**
     * Sets the value of the sdgs property.
     *
     * @param value allowed object is
     *              {@link SDGS }
     */
    public void setSDGS(final SDGS value) {
        this.sdgs = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setID(final String value) {
        this.id = value;
    }

    /**
     * Gets the value of the oid property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getOID() {
        return oid;
    }

    /**
     * Sets the value of the oid property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setOID(final String value) {
        this.oid = value;
    }

}
