//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.28 at 09:58:19 AM CET 
//


package com.javahacks.odx.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for ENV-DATA complex type.
 * <p>
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * <p>
 * &lt;pre&gt;
 * &amp;lt;complexType name="ENV-DATA"&amp;gt;
 * &amp;lt;complexContent&amp;gt;
 * &amp;lt;extension base="{}BASIC-STRUCTURE"&amp;gt;
 * &amp;lt;choice&amp;gt;
 * &amp;lt;element name="ALL-VALUE" type="{}ALL-VALUE"/&amp;gt;
 * &amp;lt;element name="DTC-VALUES" type="{}DTC-VALUES"/&amp;gt;
 * &amp;lt;/choice&amp;gt;
 * &amp;lt;/extension&amp;gt;
 * &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ENV-DATA")
public class ENVDATA
        extends BASICSTRUCTURE {

    @XmlElement(name = "ALL-VALUE")
    protected ALLVALUE allvalue;
    @XmlElement(name = "DTC-VALUES")
    protected DTCVALUES dtcvalues;

    /**
     * Gets the value of the allvalue property.
     *
     * @return possible object is
     * {@link ALLVALUE }
     */
    public ALLVALUE getALLVALUE() {
        return allvalue;
    }

    /**
     * Sets the value of the allvalue property.
     *
     * @param value allowed object is
     *              {@link ALLVALUE }
     */
    public void setALLVALUE(ALLVALUE value) {
        this.allvalue = value;
    }

    /**
     * Gets the value of the dtcvalues property.
     *
     * @return possible object is
     * {@link DTCVALUES }
     */
    public DTCVALUES getDTCVALUES() {
        return dtcvalues;
    }

    /**
     * Sets the value of the dtcvalues property.
     *
     * @param value allowed object is
     *              {@link DTCVALUES }
     */
    public void setDTCVALUES(DTCVALUES value) {
        this.dtcvalues = value;
    }

}
