//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.28 at 09:58:19 AM CET 
//


package com.javahacks.odx.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for ENV-DATA-DESC complex type.
 * <p>
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * <p>
 * &lt;pre&gt;
 * &amp;lt;complexType name="ENV-DATA-DESC"&amp;gt;
 * &amp;lt;complexContent&amp;gt;
 * &amp;lt;extension base="{}COMPLEX-DOP"&amp;gt;
 * &amp;lt;sequence&amp;gt;
 * &amp;lt;choice&amp;gt;
 * &amp;lt;element name="PARAM-SNREF" type="{}SNREF"/&amp;gt;
 * &amp;lt;element name="PARAM-SNPATHREF" type="{}SNPATHREF"/&amp;gt;
 * &amp;lt;/choice&amp;gt;
 * &amp;lt;element name="ENV-DATA-REFS" type="{}ENV-DATA-REFS"/&amp;gt;
 * &amp;lt;/sequence&amp;gt;
 * &amp;lt;/extension&amp;gt;
 * &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ENV-DATA-DESC")
public class ENVDATADESC
        extends COMPLEXDOP {

    @XmlElement(name = "PARAM-SNREF")
    protected SNREF paramsnref;
    @XmlElement(name = "PARAM-SNPATHREF")
    protected SNPATHREF paramsnpathref;
    @XmlElement(name = "ENV-DATA-REFS", required = true)
    protected ENVDATAREFS envdatarefs;

    /**
     * Gets the value of the paramsnref property.
     *
     * @return possible object is
     * {@link SNREF }
     */
    public SNREF getPARAMSNREF() {
        return paramsnref;
    }

    /**
     * Sets the value of the paramsnref property.
     *
     * @param value allowed object is
     *              {@link SNREF }
     */
    public void setPARAMSNREF(SNREF value) {
        this.paramsnref = value;
    }

    /**
     * Gets the value of the paramsnpathref property.
     *
     * @return possible object is
     * {@link SNPATHREF }
     */
    public SNPATHREF getPARAMSNPATHREF() {
        return paramsnpathref;
    }

    /**
     * Sets the value of the paramsnpathref property.
     *
     * @param value allowed object is
     *              {@link SNPATHREF }
     */
    public void setPARAMSNPATHREF(SNPATHREF value) {
        this.paramsnpathref = value;
    }

    /**
     * Gets the value of the envdatarefs property.
     *
     * @return possible object is
     * {@link ENVDATAREFS }
     */
    public ENVDATAREFS getENVDATAREFS() {
        return envdatarefs;
    }

    /**
     * Sets the value of the envdatarefs property.
     *
     * @param value allowed object is
     *              {@link ENVDATAREFS }
     */
    public void setENVDATAREFS(ENVDATAREFS value) {
        this.envdatarefs = value;
    }

}
