//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.28 at 09:58:19 AM CET 
//


package com.javahacks.odx.model;

import javax.xml.bind.annotation.*;


/**
 * &lt;p&gt;Java class for FIELD complex type.
 * <p>
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * <p>
 * &lt;pre&gt;
 * &amp;lt;complexType name="FIELD"&amp;gt;
 * &amp;lt;complexContent&amp;gt;
 * &amp;lt;extension base="{}COMPLEX-DOP"&amp;gt;
 * &amp;lt;choice&amp;gt;
 * &amp;lt;choice&amp;gt;
 * &amp;lt;element name="BASIC-STRUCTURE-REF" type="{}ODXLINK"/&amp;gt;
 * &amp;lt;element name="BASIC-STRUCTURE-SNREF" type="{}SNREF"/&amp;gt;
 * &amp;lt;/choice&amp;gt;
 * &amp;lt;choice&amp;gt;
 * &amp;lt;element name="ENV-DATA-DESC-REF" type="{}ODXLINK"/&amp;gt;
 * &amp;lt;element name="ENV-DATA-DESC-SNREF" type="{}SNREF"/&amp;gt;
 * &amp;lt;/choice&amp;gt;
 * &amp;lt;/choice&amp;gt;
 * &amp;lt;attribute name="IS-VISIBLE" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" /&amp;gt;
 * &amp;lt;/extension&amp;gt;
 * &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FIELD")
@XmlSeeAlso({
        DYNAMICENDMARKERFIELD.class,
        DYNAMICLENGTHFIELD.class,
        ENDOFPDUFIELD.class,
        STATICFIELD.class
})
public abstract class FIELD
        extends COMPLEXDOP {

    @XmlElement(name = "BASIC-STRUCTURE-REF")
    protected ODXLINK basicstructureref;
    @XmlElement(name = "BASIC-STRUCTURE-SNREF")
    protected SNREF basicstructuresnref;
    @XmlElement(name = "ENV-DATA-DESC-REF")
    protected ODXLINK envdatadescref;
    @XmlElement(name = "ENV-DATA-DESC-SNREF")
    protected SNREF envdatadescsnref;
    @XmlAttribute(name = "IS-VISIBLE")
    protected Boolean isvisible;

    /**
     * Gets the value of the basicstructureref property.
     *
     * @return possible object is
     * {@link ODXLINK }
     */
    public ODXLINK getBASICSTRUCTUREREF() {
        return basicstructureref;
    }

    /**
     * Sets the value of the basicstructureref property.
     *
     * @param value allowed object is
     *              {@link ODXLINK }
     */
    public void setBASICSTRUCTUREREF(ODXLINK value) {
        this.basicstructureref = value;
    }

    /**
     * Gets the value of the basicstructuresnref property.
     *
     * @return possible object is
     * {@link SNREF }
     */
    public SNREF getBASICSTRUCTURESNREF() {
        return basicstructuresnref;
    }

    /**
     * Sets the value of the basicstructuresnref property.
     *
     * @param value allowed object is
     *              {@link SNREF }
     */
    public void setBASICSTRUCTURESNREF(SNREF value) {
        this.basicstructuresnref = value;
    }

    /**
     * Gets the value of the envdatadescref property.
     *
     * @return possible object is
     * {@link ODXLINK }
     */
    public ODXLINK getENVDATADESCREF() {
        return envdatadescref;
    }

    /**
     * Sets the value of the envdatadescref property.
     *
     * @param value allowed object is
     *              {@link ODXLINK }
     */
    public void setENVDATADESCREF(ODXLINK value) {
        this.envdatadescref = value;
    }

    /**
     * Gets the value of the envdatadescsnref property.
     *
     * @return possible object is
     * {@link SNREF }
     */
    public SNREF getENVDATADESCSNREF() {
        return envdatadescsnref;
    }

    /**
     * Sets the value of the envdatadescsnref property.
     *
     * @param value allowed object is
     *              {@link SNREF }
     */
    public void setENVDATADESCSNREF(SNREF value) {
        this.envdatadescsnref = value;
    }

    /**
     * Gets the value of the isvisible property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public boolean isISVISIBLE() {
        if (isvisible == null) {
            return true;
        } else {
            return isvisible;
        }
    }

    /**
     * Sets the value of the isvisible property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setISVISIBLE(Boolean value) {
        this.isvisible = value;
    }

}
