//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.28 at 09:58:19 AM CET 
//


package com.javahacks.odx.model;

import com.javahacks.odx.index.AbstractLinkTarget;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * &lt;p&gt;Java class for FLASHDATA complex type.
 * <p>
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * <p>
 * &lt;pre&gt;
 * &amp;lt;complexType name="FLASHDATA"&amp;gt;
 * &amp;lt;complexContent&amp;gt;
 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 * &amp;lt;sequence&amp;gt;
 * &amp;lt;group ref="{}ELEMENT-ID"/&amp;gt;
 * &amp;lt;element name="SIZE-LENGTH" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="ADDRESS-LENGTH" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="DATAFORMAT" type="{}DATAFORMAT"/&amp;gt;
 * &amp;lt;element name="ENCRYPT-COMPRESS-METHOD" type="{}ENCRYPT-COMPRESS-METHOD" minOccurs="0"/&amp;gt;
 * &amp;lt;/sequence&amp;gt;
 * &amp;lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" /&amp;gt;
 * &amp;lt;attribute name="OID" type="{http://www.w3.org/2001/XMLSchema}string" /&amp;gt;
 * &amp;lt;/restriction&amp;gt;
 * &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FLASHDATA")
@XmlSeeAlso({
        EXTERNFLASHDATA.class,
        INTERNFLASHDATA.class
})
public abstract class FLASHDATA extends AbstractLinkTarget {

    @XmlElement(name = "SHORT-NAME", required = true)
    protected String shortname;
    @XmlElement(name = "LONG-NAME")
    protected LONGNAME longname;
    @XmlElement(name = "DESC")
    protected DESCRIPTION desc;
    @XmlElement(name = "SIZE-LENGTH")
    @XmlSchemaType(name = "unsignedInt")
    protected Long sizelength;
    @XmlElement(name = "ADDRESS-LENGTH")
    @XmlSchemaType(name = "unsignedInt")
    protected Long addresslength;
    @XmlElement(name = "DATAFORMAT", required = true)
    protected DATAFORMAT dataformat;
    @XmlElement(name = "ENCRYPT-COMPRESS-METHOD")
    protected ENCRYPTCOMPRESSMETHOD encryptcompressmethod;
    @XmlAttribute(name = "ID", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "OID")
    @XmlTransient
    protected String oid;

    /**
     * Gets the value of the shortname property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSHORTNAME() {
        return shortname;
    }

    /**
     * Sets the value of the shortname property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSHORTNAME(final String value) {
        this.shortname = value;
    }

    /**
     * Gets the value of the longname property.
     *
     * @return possible object is
     * {@link LONGNAME }
     */
    public LONGNAME getLONGNAME() {
        return longname;
    }

    /**
     * Sets the value of the longname property.
     *
     * @param value allowed object is
     *              {@link LONGNAME }
     */
    public void setLONGNAME(final LONGNAME value) {
        this.longname = value;
    }

    /**
     * Gets the value of the desc property.
     *
     * @return possible object is
     * {@link DESCRIPTION }
     */
    public DESCRIPTION getDESC() {
        return desc;
    }

    /**
     * Sets the value of the desc property.
     *
     * @param value allowed object is
     *              {@link DESCRIPTION }
     */
    public void setDESC(final DESCRIPTION value) {
        this.desc = value;
    }

    /**
     * Gets the value of the sizelength property.
     *
     * @return possible object is
     * {@link Long }
     */
    public Long getSIZELENGTH() {
        return sizelength;
    }

    /**
     * Sets the value of the sizelength property.
     *
     * @param value allowed object is
     *              {@link Long }
     */
    public void setSIZELENGTH(final Long value) {
        this.sizelength = value;
    }

    /**
     * Gets the value of the addresslength property.
     *
     * @return possible object is
     * {@link Long }
     */
    public Long getADDRESSLENGTH() {
        return addresslength;
    }

    /**
     * Sets the value of the addresslength property.
     *
     * @param value allowed object is
     *              {@link Long }
     */
    public void setADDRESSLENGTH(final Long value) {
        this.addresslength = value;
    }

    /**
     * Gets the value of the dataformat property.
     *
     * @return possible object is
     * {@link DATAFORMAT }
     */
    public DATAFORMAT getDATAFORMAT() {
        return dataformat;
    }

    /**
     * Sets the value of the dataformat property.
     *
     * @param value allowed object is
     *              {@link DATAFORMAT }
     */
    public void setDATAFORMAT(final DATAFORMAT value) {
        this.dataformat = value;
    }

    /**
     * Gets the value of the encryptcompressmethod property.
     *
     * @return possible object is
     * {@link ENCRYPTCOMPRESSMETHOD }
     */
    public ENCRYPTCOMPRESSMETHOD getENCRYPTCOMPRESSMETHOD() {
        return encryptcompressmethod;
    }

    /**
     * Sets the value of the encryptcompressmethod property.
     *
     * @param value allowed object is
     *              {@link ENCRYPTCOMPRESSMETHOD }
     */
    public void setENCRYPTCOMPRESSMETHOD(final ENCRYPTCOMPRESSMETHOD value) {
        this.encryptcompressmethod = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setID(final String value) {
        this.id = value;
    }

    /**
     * Gets the value of the oid property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getOID() {
        return oid;
    }

    /**
     * Sets the value of the oid property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setOID(final String value) {
        this.oid = value;
    }

}
