//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.28 at 09:58:19 AM CET 
//


package com.javahacks.odx.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for IDENT-VALUE-TYPE.
 * <p>
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * &lt;pre&gt;
 * &amp;lt;simpleType name="IDENT-VALUE-TYPE"&amp;gt;
 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt;
 * &amp;lt;enumeration value="A_UINT32"/&amp;gt;
 * &amp;lt;enumeration value="A_BYTEFIELD"/&amp;gt;
 * &amp;lt;enumeration value="A_ASCIISTRING"/&amp;gt;
 * &amp;lt;/restriction&amp;gt;
 * &amp;lt;/simpleType&amp;gt;
 * &lt;/pre&gt;
 */
@XmlType(name = "IDENT-VALUE-TYPE")
@XmlEnum
public enum IDENTVALUETYPE {

    @XmlEnumValue("A_UINT32")
    A_UINT_32("A_UINT32"),
    A_BYTEFIELD("A_BYTEFIELD"),
    A_ASCIISTRING("A_ASCIISTRING");
    private final String value;

    IDENTVALUETYPE(String v) {
        value = v;
    }

    public static IDENTVALUETYPE fromValue(String v) {
        for (IDENTVALUETYPE c : IDENTVALUETYPE.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

    public String value() {
        return value;
    }

}
