//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.28 at 09:58:19 AM CET 
//


package com.javahacks.odx.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for INTERVAL-TYPE.
 * <p>
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * &lt;pre&gt;
 * &amp;lt;simpleType name="INTERVAL-TYPE"&amp;gt;
 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt;
 * &amp;lt;enumeration value="OPEN"/&amp;gt;
 * &amp;lt;enumeration value="CLOSED"/&amp;gt;
 * &amp;lt;enumeration value="INFINITE"/&amp;gt;
 * &amp;lt;/restriction&amp;gt;
 * &amp;lt;/simpleType&amp;gt;
 * &lt;/pre&gt;
 */
@XmlType(name = "INTERVAL-TYPE")
@XmlEnum
public enum INTERVALTYPE {

    OPEN,
    CLOSED,
    INFINITE;

    public static INTERVALTYPE fromValue(String v) {
        return valueOf(v);
    }

    public String value() {
        return name();
    }

}
