//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.28 at 09:58:19 AM CET 
//


package com.javahacks.odx.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for ITEM-VALUE complex type.
 * <p>
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * <p>
 * &lt;pre&gt;
 * &amp;lt;complexType name="ITEM-VALUE"&amp;gt;
 * &amp;lt;complexContent&amp;gt;
 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 * &amp;lt;sequence&amp;gt;
 * &amp;lt;element name="PHYS-CONSTANT-VALUE" type="{http://www.w3.org/2001/XMLSchema}string"/&amp;gt;
 * &amp;lt;element name="MEANING" type="{}TEXT" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="KEY" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="RULE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="DESCRIPTION" type="{}TEXT" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="SDGS" type="{}SDGS" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="AUDIENCE" type="{}AUDIENCE" minOccurs="0"/&amp;gt;
 * &amp;lt;/sequence&amp;gt;
 * &amp;lt;/restriction&amp;gt;
 * &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ITEM-VALUE")
public class ITEMVALUE {

    @XmlElement(name = "PHYS-CONSTANT-VALUE", required = true)
    protected String physconstantvalue;
    @XmlElement(name = "MEANING")
    protected TEXT meaning;
    @XmlElement(name = "KEY")
    protected String key;
    @XmlElement(name = "RULE")
    protected String rule;
    @XmlElement(name = "DESCRIPTION")
    protected TEXT description;
    @XmlElement(name = "SDGS")
    protected SDGS sdgs;
    @XmlElement(name = "AUDIENCE")
    protected AUDIENCE audience;

    /**
     * Gets the value of the physconstantvalue property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPHYSCONSTANTVALUE() {
        return physconstantvalue;
    }

    /**
     * Sets the value of the physconstantvalue property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPHYSCONSTANTVALUE(String value) {
        this.physconstantvalue = value;
    }

    /**
     * Gets the value of the meaning property.
     *
     * @return possible object is
     * {@link TEXT }
     */
    public TEXT getMEANING() {
        return meaning;
    }

    /**
     * Sets the value of the meaning property.
     *
     * @param value allowed object is
     *              {@link TEXT }
     */
    public void setMEANING(TEXT value) {
        this.meaning = value;
    }

    /**
     * Gets the value of the key property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getKEY() {
        return key;
    }

    /**
     * Sets the value of the key property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setKEY(String value) {
        this.key = value;
    }

    /**
     * Gets the value of the rule property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getRULE() {
        return rule;
    }

    /**
     * Sets the value of the rule property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRULE(String value) {
        this.rule = value;
    }

    /**
     * Gets the value of the description property.
     *
     * @return possible object is
     * {@link TEXT }
     */
    public TEXT getDESCRIPTION() {
        return description;
    }

    /**
     * Sets the value of the description property.
     *
     * @param value allowed object is
     *              {@link TEXT }
     */
    public void setDESCRIPTION(TEXT value) {
        this.description = value;
    }

    /**
     * Gets the value of the sdgs property.
     *
     * @return possible object is
     * {@link SDGS }
     */
    public SDGS getSDGS() {
        return sdgs;
    }

    /**
     * Sets the value of the sdgs property.
     *
     * @param value allowed object is
     *              {@link SDGS }
     */
    public void setSDGS(SDGS value) {
        this.sdgs = value;
    }

    /**
     * Gets the value of the audience property.
     *
     * @return possible object is
     * {@link AUDIENCE }
     */
    public AUDIENCE getAUDIENCE() {
        return audience;
    }

    /**
     * Sets the value of the audience property.
     *
     * @param value allowed object is
     *              {@link AUDIENCE }
     */
    public void setAUDIENCE(AUDIENCE value) {
        this.audience = value;
    }

}
