//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.28 at 09:58:19 AM CET 
//


package com.javahacks.odx.model;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * &lt;p&gt;Java class for LIBRARY complex type.
 * <p>
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * <p>
 * &lt;pre&gt;
 * &amp;lt;complexType name="LIBRARY"&amp;gt;
 * &amp;lt;complexContent&amp;gt;
 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 * &amp;lt;sequence&amp;gt;
 * &amp;lt;group ref="{}ELEMENT-ID"/&amp;gt;
 * &amp;lt;element name="CODE-FILE" type="{http://www.w3.org/2001/XMLSchema}string"/&amp;gt;
 * &amp;lt;element name="ENCRYPTION" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="SYNTAX" type="{http://www.w3.org/2001/XMLSchema}string"/&amp;gt;
 * &amp;lt;element name="REVISION" type="{http://www.w3.org/2001/XMLSchema}string"/&amp;gt;
 * &amp;lt;element name="ENTRYPOINT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&amp;gt;
 * &amp;lt;/sequence&amp;gt;
 * &amp;lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" /&amp;gt;
 * &amp;lt;attribute name="OID" type="{http://www.w3.org/2001/XMLSchema}string" /&amp;gt;
 * &amp;lt;/restriction&amp;gt;
 * &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LIBRARY")
public class LIBRARY {

    @XmlElement(name = "SHORT-NAME", required = true)
    protected String shortname;
    @XmlElement(name = "LONG-NAME")
    protected LONGNAME longname;
    @XmlElement(name = "DESC")
    protected DESCRIPTION desc;
    @XmlElement(name = "CODE-FILE", required = true)
    protected String codefile;
    @XmlElement(name = "ENCRYPTION")
    protected String encryption;
    @XmlElement(name = "SYNTAX", required = true)
    protected String syntax;
    @XmlElement(name = "REVISION", required = true)
    protected String revision;
    @XmlElement(name = "ENTRYPOINT")
    protected String entrypoint;
    @XmlAttribute(name = "ID", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "OID")
    @XmlTransient
    protected String oid;

    /**
     * Gets the value of the shortname property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSHORTNAME() {
        return shortname;
    }

    /**
     * Sets the value of the shortname property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSHORTNAME(final String value) {
        this.shortname = value;
    }

    /**
     * Gets the value of the longname property.
     *
     * @return possible object is
     * {@link LONGNAME }
     */
    public LONGNAME getLONGNAME() {
        return longname;
    }

    /**
     * Sets the value of the longname property.
     *
     * @param value allowed object is
     *              {@link LONGNAME }
     */
    public void setLONGNAME(final LONGNAME value) {
        this.longname = value;
    }

    /**
     * Gets the value of the desc property.
     *
     * @return possible object is
     * {@link DESCRIPTION }
     */
    public DESCRIPTION getDESC() {
        return desc;
    }

    /**
     * Sets the value of the desc property.
     *
     * @param value allowed object is
     *              {@link DESCRIPTION }
     */
    public void setDESC(final DESCRIPTION value) {
        this.desc = value;
    }

    /**
     * Gets the value of the codefile property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCODEFILE() {
        return codefile;
    }

    /**
     * Sets the value of the codefile property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCODEFILE(final String value) {
        this.codefile = value;
    }

    /**
     * Gets the value of the encryption property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getENCRYPTION() {
        return encryption;
    }

    /**
     * Sets the value of the encryption property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setENCRYPTION(final String value) {
        this.encryption = value;
    }

    /**
     * Gets the value of the syntax property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSYNTAX() {
        return syntax;
    }

    /**
     * Sets the value of the syntax property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSYNTAX(final String value) {
        this.syntax = value;
    }

    /**
     * Gets the value of the revision property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getREVISION() {
        return revision;
    }

    /**
     * Sets the value of the revision property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setREVISION(final String value) {
        this.revision = value;
    }

    /**
     * Gets the value of the entrypoint property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getENTRYPOINT() {
        return entrypoint;
    }

    /**
     * Sets the value of the entrypoint property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setENTRYPOINT(final String value) {
        this.entrypoint = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setID(final String value) {
        this.id = value;
    }

    /**
     * Gets the value of the oid property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getOID() {
        return oid;
    }

    /**
     * Sets the value of the oid property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setOID(final String value) {
        this.oid = value;
    }

}
