//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.28 at 09:58:19 AM CET 
//


package com.javahacks.odx.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for LINKED-DTC-DOP complex type.
 * <p>
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * <p>
 * &lt;pre&gt;
 * &amp;lt;complexType name="LINKED-DTC-DOP"&amp;gt;
 * &amp;lt;complexContent&amp;gt;
 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 * &amp;lt;sequence&amp;gt;
 * &amp;lt;element name="NOT-INHERITED-DTC-SNREFS" type="{}NOT-INHERITED-DTC-SNREFS" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="DTC-DOP-REF" type="{}ODXLINK"/&amp;gt;
 * &amp;lt;/sequence&amp;gt;
 * &amp;lt;/restriction&amp;gt;
 * &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LINKED-DTC-DOP")
public class LINKEDDTCDOP {

    @XmlElement(name = "NOT-INHERITED-DTC-SNREFS")
    protected NOTINHERITEDDTCSNREFS notinheriteddtcsnrefs;
    @XmlElement(name = "DTC-DOP-REF", required = true)
    protected ODXLINK dtcdopref;

    /**
     * Gets the value of the notinheriteddtcsnrefs property.
     *
     * @return possible object is
     * {@link NOTINHERITEDDTCSNREFS }
     */
    public NOTINHERITEDDTCSNREFS getNOTINHERITEDDTCSNREFS() {
        return notinheriteddtcsnrefs;
    }

    /**
     * Sets the value of the notinheriteddtcsnrefs property.
     *
     * @param value allowed object is
     *              {@link NOTINHERITEDDTCSNREFS }
     */
    public void setNOTINHERITEDDTCSNREFS(NOTINHERITEDDTCSNREFS value) {
        this.notinheriteddtcsnrefs = value;
    }

    /**
     * Gets the value of the dtcdopref property.
     *
     * @return possible object is
     * {@link ODXLINK }
     */
    public ODXLINK getDTCDOPREF() {
        return dtcdopref;
    }

    /**
     * Sets the value of the dtcdopref property.
     *
     * @param value allowed object is
     *              {@link ODXLINK }
     */
    public void setDTCDOPREF(ODXLINK value) {
        this.dtcdopref = value;
    }

}
