//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.28 at 09:58:19 AM CET 
//


package com.javahacks.odx.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for MATCHING-COMPONENT complex type.
 * <p>
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * <p>
 * &lt;pre&gt;
 * &amp;lt;complexType name="MATCHING-COMPONENT"&amp;gt;
 * &amp;lt;complexContent&amp;gt;
 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 * &amp;lt;sequence&amp;gt;
 * &amp;lt;element name="EXPECTED-VALUE" type="{http://www.w3.org/2001/XMLSchema}string"/&amp;gt;
 * &amp;lt;choice&amp;gt;
 * &amp;lt;element name="OUT-PARAM-IF-SNREF" type="{}SNREF"/&amp;gt;
 * &amp;lt;element name="OUT-PARAM-IF-SNPATHREF" type="{}SNPATHREF"/&amp;gt;
 * &amp;lt;/choice&amp;gt;
 * &amp;lt;choice&amp;gt;
 * &amp;lt;element name="MULTIPLE-ECU-JOB-REF" type="{}ODXLINK"/&amp;gt;
 * &amp;lt;element name="DIAG-COMM-REF" type="{}ODXLINK"/&amp;gt;
 * &amp;lt;/choice&amp;gt;
 * &amp;lt;/sequence&amp;gt;
 * &amp;lt;/restriction&amp;gt;
 * &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MATCHING-COMPONENT")
public class MATCHINGCOMPONENT {

    @XmlElement(name = "EXPECTED-VALUE", required = true)
    protected String expectedvalue;
    @XmlElement(name = "OUT-PARAM-IF-SNREF")
    protected SNREF outparamifsnref;
    @XmlElement(name = "OUT-PARAM-IF-SNPATHREF")
    protected SNPATHREF outparamifsnpathref;
    @XmlElement(name = "MULTIPLE-ECU-JOB-REF")
    protected ODXLINK multipleecujobref;
    @XmlElement(name = "DIAG-COMM-REF")
    protected ODXLINK diagcommref;

    /**
     * Gets the value of the expectedvalue property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getEXPECTEDVALUE() {
        return expectedvalue;
    }

    /**
     * Sets the value of the expectedvalue property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setEXPECTEDVALUE(String value) {
        this.expectedvalue = value;
    }

    /**
     * Gets the value of the outparamifsnref property.
     *
     * @return possible object is
     * {@link SNREF }
     */
    public SNREF getOUTPARAMIFSNREF() {
        return outparamifsnref;
    }

    /**
     * Sets the value of the outparamifsnref property.
     *
     * @param value allowed object is
     *              {@link SNREF }
     */
    public void setOUTPARAMIFSNREF(SNREF value) {
        this.outparamifsnref = value;
    }

    /**
     * Gets the value of the outparamifsnpathref property.
     *
     * @return possible object is
     * {@link SNPATHREF }
     */
    public SNPATHREF getOUTPARAMIFSNPATHREF() {
        return outparamifsnpathref;
    }

    /**
     * Sets the value of the outparamifsnpathref property.
     *
     * @param value allowed object is
     *              {@link SNPATHREF }
     */
    public void setOUTPARAMIFSNPATHREF(SNPATHREF value) {
        this.outparamifsnpathref = value;
    }

    /**
     * Gets the value of the multipleecujobref property.
     *
     * @return possible object is
     * {@link ODXLINK }
     */
    public ODXLINK getMULTIPLEECUJOBREF() {
        return multipleecujobref;
    }

    /**
     * Sets the value of the multipleecujobref property.
     *
     * @param value allowed object is
     *              {@link ODXLINK }
     */
    public void setMULTIPLEECUJOBREF(ODXLINK value) {
        this.multipleecujobref = value;
    }

    /**
     * Gets the value of the diagcommref property.
     *
     * @return possible object is
     * {@link ODXLINK }
     */
    public ODXLINK getDIAGCOMMREF() {
        return diagcommref;
    }

    /**
     * Sets the value of the diagcommref property.
     *
     * @param value allowed object is
     *              {@link ODXLINK }
     */
    public void setDIAGCOMMREF(ODXLINK value) {
        this.diagcommref = value;
    }

}
