//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.28 at 09:58:19 AM CET 
//


package com.javahacks.odx.model;

import javax.xml.bind.annotation.*;


/**
 * &lt;p&gt;Java class for MIN-MAX-LENGTH-TYPE complex type.
 * <p>
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * <p>
 * &lt;pre&gt;
 * &amp;lt;complexType name="MIN-MAX-LENGTH-TYPE"&amp;gt;
 * &amp;lt;complexContent&amp;gt;
 * &amp;lt;extension base="{}DIAG-CODED-TYPE"&amp;gt;
 * &amp;lt;sequence&amp;gt;
 * &amp;lt;element name="MAX-LENGTH" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="MIN-LENGTH" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/&amp;gt;
 * &amp;lt;/sequence&amp;gt;
 * &amp;lt;attribute name="TERMINATION" use="required" type="{}TERMINATION" /&amp;gt;
 * &amp;lt;/extension&amp;gt;
 * &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MIN-MAX-LENGTH-TYPE")
public class MINMAXLENGTHTYPE
        extends DIAGCODEDTYPE {

    @XmlElement(name = "MAX-LENGTH")
    @XmlSchemaType(name = "unsignedInt")
    protected Long maxlength;
    @XmlElement(name = "MIN-LENGTH")
    @XmlSchemaType(name = "unsignedInt")
    protected long minlength;
    @XmlAttribute(name = "TERMINATION", required = true)
    protected TERMINATION termination;

    /**
     * Gets the value of the maxlength property.
     *
     * @return possible object is
     * {@link Long }
     */
    public Long getMAXLENGTH() {
        return maxlength;
    }

    /**
     * Sets the value of the maxlength property.
     *
     * @param value allowed object is
     *              {@link Long }
     */
    public void setMAXLENGTH(final Long value) {
        this.maxlength = value;
    }

    /**
     * Gets the value of the minlength property.
     */
    public long getMINLENGTH() {
        return minlength;
    }

    /**
     * Sets the value of the minlength property.
     */
    public void setMINLENGTH(final long value) {
        this.minlength = value;
    }

    /**
     * Gets the value of the termination property.
     *
     * @return possible object is
     * {@link TERMINATION }
     */
    public TERMINATION getTERMINATION() {
        return termination;
    }

    /**
     * Sets the value of the termination property.
     *
     * @param value allowed object is
     *              {@link TERMINATION }
     */
    public void setTERMINATION(final TERMINATION value) {
        this.termination = value;
    }

}
