//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.28 at 09:58:19 AM CET 
//


package com.javahacks.odx.model;

import javax.xml.bind.annotation.*;


/**
 * &lt;p&gt;Java class for MUX complex type.
 * <p>
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * <p>
 * &lt;pre&gt;
 * &amp;lt;complexType name="MUX"&amp;gt;
 * &amp;lt;complexContent&amp;gt;
 * &amp;lt;extension base="{}COMPLEX-DOP"&amp;gt;
 * &amp;lt;sequence&amp;gt;
 * &amp;lt;element name="BYTE-POSITION" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/&amp;gt;
 * &amp;lt;element name="SWITCH-KEY" type="{}SWITCH-KEY"/&amp;gt;
 * &amp;lt;element name="DEFAULT-CASE" type="{}DEFAULT-CASE" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="CASES" type="{}CASES" minOccurs="0"/&amp;gt;
 * &amp;lt;/sequence&amp;gt;
 * &amp;lt;attribute name="IS-VISIBLE" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&amp;gt;
 * &amp;lt;/extension&amp;gt;
 * &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MUX")
public class MUX
        extends COMPLEXDOP {

    @XmlElement(name = "BYTE-POSITION")
    @XmlSchemaType(name = "unsignedInt")
    protected long byteposition;
    @XmlElement(name = "SWITCH-KEY", required = true)
    protected SWITCHKEY switchkey;
    @XmlElement(name = "DEFAULT-CASE")
    protected DEFAULTCASE defaultcase;
    @XmlElement(name = "CASES")
    protected CASES cases;
    @XmlAttribute(name = "IS-VISIBLE")
    protected Boolean isvisible;

    /**
     * Gets the value of the byteposition property.
     */
    public long getBYTEPOSITION() {
        return byteposition;
    }

    /**
     * Sets the value of the byteposition property.
     */
    public void setBYTEPOSITION(long value) {
        this.byteposition = value;
    }

    /**
     * Gets the value of the switchkey property.
     *
     * @return possible object is
     * {@link SWITCHKEY }
     */
    public SWITCHKEY getSWITCHKEY() {
        return switchkey;
    }

    /**
     * Sets the value of the switchkey property.
     *
     * @param value allowed object is
     *              {@link SWITCHKEY }
     */
    public void setSWITCHKEY(SWITCHKEY value) {
        this.switchkey = value;
    }

    /**
     * Gets the value of the defaultcase property.
     *
     * @return possible object is
     * {@link DEFAULTCASE }
     */
    public DEFAULTCASE getDEFAULTCASE() {
        return defaultcase;
    }

    /**
     * Sets the value of the defaultcase property.
     *
     * @param value allowed object is
     *              {@link DEFAULTCASE }
     */
    public void setDEFAULTCASE(DEFAULTCASE value) {
        this.defaultcase = value;
    }

    /**
     * Gets the value of the cases property.
     *
     * @return possible object is
     * {@link CASES }
     */
    public CASES getCASES() {
        return cases;
    }

    /**
     * Sets the value of the cases property.
     *
     * @param value allowed object is
     *              {@link CASES }
     */
    public void setCASES(CASES value) {
        this.cases = value;
    }

    /**
     * Gets the value of the isvisible property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public boolean isISVISIBLE() {
        if (isvisible == null) {
            return false;
        } else {
            return isvisible;
        }
    }

    /**
     * Sets the value of the isvisible property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setISVISIBLE(Boolean value) {
        this.isvisible = value;
    }

}
