//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.28 at 09:58:19 AM CET 
//


package com.javahacks.odx.model;

import javax.xml.bind.annotation.*;


/**
 * &lt;p&gt;Java class for ODX complex type.
 * <p>
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * <p>
 * &lt;pre&gt;
 * &amp;lt;complexType name="ODX"&amp;gt;
 * &amp;lt;complexContent&amp;gt;
 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 * &amp;lt;choice&amp;gt;
 * &amp;lt;element name="DIAG-LAYER-CONTAINER" type="{}DIAG-LAYER-CONTAINER"/&amp;gt;
 * &amp;lt;element name="COMPARAM-SPEC" type="{}COMPARAM-SPEC"/&amp;gt;
 * &amp;lt;element name="VEHICLE-INFO-SPEC" type="{}VEHICLE-INFO-SPEC"/&amp;gt;
 * &amp;lt;element name="FLASH" type="{}FLASH"/&amp;gt;
 * &amp;lt;element name="ECU-CONFIG" type="{}ECU-CONFIG"/&amp;gt;
 * &amp;lt;element name="MULTIPLE-ECU-JOB-SPEC" type="{}MULTIPLE-ECU-JOB-SPEC"/&amp;gt;
 * &amp;lt;element name="COMPARAM-SUBSET" type="{}COMPARAM-SUBSET"/&amp;gt;
 * &amp;lt;element name="FUNCTION-DICTIONARY" type="{}FUNCTION-DICTIONARY"/&amp;gt;
 * &amp;lt;/choice&amp;gt;
 * &amp;lt;attribute name="MODEL-VERSION" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="2.2.0" /&amp;gt;
 * &amp;lt;/restriction&amp;gt;
 * &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ODX")
@XmlRootElement
public class ODX {

    @XmlElement(name = "DIAG-LAYER-CONTAINER")
    protected DIAGLAYERCONTAINER diaglayercontainer;
    @XmlElement(name = "COMPARAM-SPEC")
    protected COMPARAMSPEC comparamspec;
    @XmlElement(name = "VEHICLE-INFO-SPEC")
    protected VEHICLEINFOSPEC vehicleinfospec;
    @XmlElement(name = "FLASH")
    protected FLASH flash;
    @XmlElement(name = "ECU-CONFIG")
    protected ECUCONFIG ecuconfig;
    @XmlElement(name = "MULTIPLE-ECU-JOB-SPEC")
    protected MULTIPLEECUJOBSPEC multipleecujobspec;
    @XmlElement(name = "COMPARAM-SUBSET")
    protected COMPARAMSUBSET comparamsubset;
    @XmlElement(name = "FUNCTION-DICTIONARY")
    protected FUNCTIONDICTIONARY functiondictionary;
    @XmlAttribute(name = "MODEL-VERSION", required = true)
    protected String modelversion;

    public ODX() {

    }

    /**
     * Gets the value of the diaglayercontainer property.
     *
     * @return possible object is
     * {@link DIAGLAYERCONTAINER }
     */
    public DIAGLAYERCONTAINER getDIAGLAYERCONTAINER() {
        return diaglayercontainer;
    }

    /**
     * Sets the value of the diaglayercontainer property.
     *
     * @param value allowed object is
     *              {@link DIAGLAYERCONTAINER }
     */
    public void setDIAGLAYERCONTAINER(final DIAGLAYERCONTAINER value) {
        this.diaglayercontainer = value;
    }

    /**
     * Gets the value of the comparamspec property.
     *
     * @return possible object is
     * {@link COMPARAMSPEC }
     */
    public COMPARAMSPEC getCOMPARAMSPEC() {
        return comparamspec;
    }

    /**
     * Sets the value of the comparamspec property.
     *
     * @param value allowed object is
     *              {@link COMPARAMSPEC }
     */
    public void setCOMPARAMSPEC(final COMPARAMSPEC value) {
        this.comparamspec = value;
    }

    /**
     * Gets the value of the vehicleinfospec property.
     *
     * @return possible object is
     * {@link VEHICLEINFOSPEC }
     */
    public VEHICLEINFOSPEC getVEHICLEINFOSPEC() {
        return vehicleinfospec;
    }

    /**
     * Sets the value of the vehicleinfospec property.
     *
     * @param value allowed object is
     *              {@link VEHICLEINFOSPEC }
     */
    public void setVEHICLEINFOSPEC(final VEHICLEINFOSPEC value) {
        this.vehicleinfospec = value;
    }

    /**
     * Gets the value of the flash property.
     *
     * @return possible object is
     * {@link FLASH }
     */
    public FLASH getFLASH() {
        return flash;
    }

    /**
     * Sets the value of the flash property.
     *
     * @param value allowed object is
     *              {@link FLASH }
     */
    public void setFLASH(final FLASH value) {
        this.flash = value;
    }

    /**
     * Gets the value of the ecuconfig property.
     *
     * @return possible object is
     * {@link ECUCONFIG }
     */
    public ECUCONFIG getECUCONFIG() {
        return ecuconfig;
    }

    /**
     * Sets the value of the ecuconfig property.
     *
     * @param value allowed object is
     *              {@link ECUCONFIG }
     */
    public void setECUCONFIG(final ECUCONFIG value) {
        this.ecuconfig = value;
    }

    /**
     * Gets the value of the multipleecujobspec property.
     *
     * @return possible object is
     * {@link MULTIPLEECUJOBSPEC }
     */
    public MULTIPLEECUJOBSPEC getMULTIPLEECUJOBSPEC() {
        return multipleecujobspec;
    }

    /**
     * Sets the value of the multipleecujobspec property.
     *
     * @param value allowed object is
     *              {@link MULTIPLEECUJOBSPEC }
     */
    public void setMULTIPLEECUJOBSPEC(final MULTIPLEECUJOBSPEC value) {
        this.multipleecujobspec = value;
    }

    /**
     * Gets the value of the comparamsubset property.
     *
     * @return possible object is
     * {@link COMPARAMSUBSET }
     */
    public COMPARAMSUBSET getCOMPARAMSUBSET() {
        return comparamsubset;
    }

    /**
     * Sets the value of the comparamsubset property.
     *
     * @param value allowed object is
     *              {@link COMPARAMSUBSET }
     */
    public void setCOMPARAMSUBSET(final COMPARAMSUBSET value) {
        this.comparamsubset = value;
    }

    /**
     * Gets the value of the functiondictionary property.
     *
     * @return possible object is
     * {@link FUNCTIONDICTIONARY }
     */
    public FUNCTIONDICTIONARY getFUNCTIONDICTIONARY() {
        return functiondictionary;
    }

    /**
     * Sets the value of the functiondictionary property.
     *
     * @param value allowed object is
     *              {@link FUNCTIONDICTIONARY }
     */
    public void setFUNCTIONDICTIONARY(final FUNCTIONDICTIONARY value) {
        this.functiondictionary = value;
    }

    /**
     * Gets the value of the modelversion property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getMODELVERSION() {
        if (modelversion == null) {
            return "2.2.0";
        } else {
            return modelversion;
        }
    }

    /**
     * Sets the value of the modelversion property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setMODELVERSION(final String value) {
        this.modelversion = value;
    }

}
