//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.28 at 09:58:19 AM CET 
//


package com.javahacks.odx.model;

import com.javahacks.odx.index.AbstractLink;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import java.util.Objects;


/**
 * &lt;p&gt;Java class for ODXLINK complex type.
 * <p>
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * <p>
 * &lt;pre&gt;
 * &amp;lt;complexType name="ODXLINK"&amp;gt;
 * &amp;lt;complexContent&amp;gt;
 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 * &amp;lt;attGroup ref="{}ODXLINK-ATTR"/&amp;gt;
 * &amp;lt;/restriction&amp;gt;
 * &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ODXLINK")
public class ODXLINK extends AbstractLink {

    @XmlAttribute(name = "DOCREF")
    protected String docref;
    @XmlAttribute(name = "DOCTYPE")
    protected DOCTYPE doctype;
    @XmlAttribute(name = "REVISION")
    protected String revision;
    @XmlAttribute(name = "ID-REF", required = true)
    private String idref;

    /**
     * Gets the value of the idref property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getIDREF() {
        return idref;
    }

    /**
     * Sets the value of the idref property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setIDREF(final String value) {
        this.idref = value;
    }

    /**
     * Gets the value of the docref property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDOCREF() {
        return docref;
    }

    /**
     * Sets the value of the docref property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDOCREF(final String value) {
        this.docref = value;
    }

    /**
     * Gets the value of the doctype property.
     *
     * @return possible object is
     * {@link DOCTYPE }
     */
    public DOCTYPE getDOCTYPE() {
        return doctype;
    }

    /**
     * Sets the value of the doctype property.
     *
     * @param value allowed object is
     *              {@link DOCTYPE }
     */
    public void setDOCTYPE(final DOCTYPE value) {
        this.doctype = value;
    }

    /**
     * Gets the value of the revision property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getREVISION() {
        return revision;
    }

    /**
     * Sets the value of the revision property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setREVISION(final String value) {
        this.revision = value;
    }

    @Override
    public String toString() {
        return "ODXLINK{" +
                "idref='" + idref + '\'' +
                ", docref='" + docref + '\'' +
                ", doctype=" + doctype +
                '}';
    }

    @Override
    public boolean equals(final Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        final ODXLINK odxlink = (ODXLINK) o;
        return Objects.equals(docref, odxlink.docref) && doctype == odxlink.doctype && Objects.equals(idref, odxlink.idref);
    }

    @Override
    public int hashCode() {
        return Objects.hash(docref, doctype, idref);
    }
}
