//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.28 at 09:58:19 AM CET 
//


package com.javahacks.odx.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for PROG-CODE complex type.
 * <p>
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * <p>
 * &lt;pre&gt;
 * &amp;lt;complexType name="PROG-CODE"&amp;gt;
 * &amp;lt;complexContent&amp;gt;
 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 * &amp;lt;sequence&amp;gt;
 * &amp;lt;element name="CODE-FILE" type="{http://www.w3.org/2001/XMLSchema}string"/&amp;gt;
 * &amp;lt;element name="ENCRYPTION" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="SYNTAX" type="{http://www.w3.org/2001/XMLSchema}string"/&amp;gt;
 * &amp;lt;element name="REVISION" type="{http://www.w3.org/2001/XMLSchema}string"/&amp;gt;
 * &amp;lt;element name="ENTRYPOINT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="LIBRARY-REFS" type="{}LIBRARY-REFS" minOccurs="0"/&amp;gt;
 * &amp;lt;/sequence&amp;gt;
 * &amp;lt;/restriction&amp;gt;
 * &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PROG-CODE")
public class PROGCODE {

    @XmlElement(name = "CODE-FILE", required = true)
    protected String codefile;
    @XmlElement(name = "ENCRYPTION")
    protected String encryption;
    @XmlElement(name = "SYNTAX", required = true)
    protected String syntax;
    @XmlElement(name = "REVISION", required = true)
    protected String revision;
    @XmlElement(name = "ENTRYPOINT")
    protected String entrypoint;
    @XmlElement(name = "LIBRARY-REFS")
    protected LIBRARYREFS libraryrefs;

    /**
     * Gets the value of the codefile property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCODEFILE() {
        return codefile;
    }

    /**
     * Sets the value of the codefile property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCODEFILE(String value) {
        this.codefile = value;
    }

    /**
     * Gets the value of the encryption property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getENCRYPTION() {
        return encryption;
    }

    /**
     * Sets the value of the encryption property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setENCRYPTION(String value) {
        this.encryption = value;
    }

    /**
     * Gets the value of the syntax property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSYNTAX() {
        return syntax;
    }

    /**
     * Sets the value of the syntax property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSYNTAX(String value) {
        this.syntax = value;
    }

    /**
     * Gets the value of the revision property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getREVISION() {
        return revision;
    }

    /**
     * Sets the value of the revision property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setREVISION(String value) {
        this.revision = value;
    }

    /**
     * Gets the value of the entrypoint property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getENTRYPOINT() {
        return entrypoint;
    }

    /**
     * Sets the value of the entrypoint property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setENTRYPOINT(String value) {
        this.entrypoint = value;
    }

    /**
     * Gets the value of the libraryrefs property.
     *
     * @return possible object is
     * {@link LIBRARYREFS }
     */
    public LIBRARYREFS getLIBRARYREFS() {
        return libraryrefs;
    }

    /**
     * Sets the value of the libraryrefs property.
     *
     * @param value allowed object is
     *              {@link LIBRARYREFS }
     */
    public void setLIBRARYREFS(LIBRARYREFS value) {
        this.libraryrefs = value;
    }

}
