//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.28 at 09:58:19 AM CET 
//


package com.javahacks.odx.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for PROTOCOL complex type.
 * <p>
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * <p>
 * &lt;pre&gt;
 * &amp;lt;complexType name="PROTOCOL"&amp;gt;
 * &amp;lt;complexContent&amp;gt;
 * &amp;lt;extension base="{}HIERARCHY-ELEMENT"&amp;gt;
 * &amp;lt;sequence&amp;gt;
 * &amp;lt;element name="COMPARAM-SPEC-REF" type="{}ODXLINK"/&amp;gt;
 * &amp;lt;element name="PROT-STACK-SNREF" type="{}SNREF" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="PARENT-REFS" type="{}PARENT-REFS" minOccurs="0"/&amp;gt;
 * &amp;lt;/sequence&amp;gt;
 * &amp;lt;/extension&amp;gt;
 * &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PROTOCOL")
public class PROTOCOL
        extends HIERARCHYELEMENT {

    @XmlElement(name = "COMPARAM-SPEC-REF", required = true)
    protected ODXLINK comparamspecref;
    @XmlElement(name = "PROT-STACK-SNREF")
    protected SNREF protstacksnref;

    /**
     * Gets the value of the comparamspecref property.
     *
     * @return possible object is
     * {@link ODXLINK }
     */
    public ODXLINK getCOMPARAMSPECREF() {
        return comparamspecref;
    }

    /**
     * Sets the value of the comparamspecref property.
     *
     * @param value allowed object is
     *              {@link ODXLINK }
     */
    public void setCOMPARAMSPECREF(final ODXLINK value) {
        this.comparamspecref = value;
    }

    /**
     * Gets the value of the protstacksnref property.
     *
     * @return possible object is
     * {@link SNREF }
     */
    public SNREF getPROTSTACKSNREF() {
        return protstacksnref;
    }

    /**
     * Sets the value of the protstacksnref property.
     *
     * @param value allowed object is
     *              {@link SNREF }
     */
    public void setPROTSTACKSNREF(final SNREF value) {
        this.protstacksnref = value;
    }


}
