//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.28 at 09:58:19 AM CET 
//


package com.javahacks.odx.model;

import javax.xml.bind.annotation.*;


/**
 * &lt;p&gt;Java class for READ-PARAM-VALUE complex type.
 * <p>
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * <p>
 * &lt;pre&gt;
 * &amp;lt;complexType name="READ-PARAM-VALUE"&amp;gt;
 * &amp;lt;complexContent&amp;gt;
 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 * &amp;lt;sequence&amp;gt;
 * &amp;lt;element name="PHYS-CONSTANT-VALUE" type="{http://www.w3.org/2001/XMLSchema}string"/&amp;gt;
 * &amp;lt;choice&amp;gt;
 * &amp;lt;element name="IN-PARAM-IF-SNREF" type="{}SNREF"/&amp;gt;
 * &amp;lt;element name="IN-PARAM-IF-SNPATHREF" type="{}SNPATHREF"/&amp;gt;
 * &amp;lt;/choice&amp;gt;
 * &amp;lt;/sequence&amp;gt;
 * &amp;lt;attribute name="SEMANTIC" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&amp;gt;
 * &amp;lt;/restriction&amp;gt;
 * &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "READ-PARAM-VALUE")
public class READPARAMVALUE {

    @XmlElement(name = "PHYS-CONSTANT-VALUE", required = true)
    protected String physconstantvalue;
    @XmlElement(name = "IN-PARAM-IF-SNREF")
    protected SNREF inparamifsnref;
    @XmlElement(name = "IN-PARAM-IF-SNPATHREF")
    protected SNPATHREF inparamifsnpathref;
    @XmlAttribute(name = "SEMANTIC", required = true)
    protected String semantic;

    /**
     * Gets the value of the physconstantvalue property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPHYSCONSTANTVALUE() {
        return physconstantvalue;
    }

    /**
     * Sets the value of the physconstantvalue property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPHYSCONSTANTVALUE(String value) {
        this.physconstantvalue = value;
    }

    /**
     * Gets the value of the inparamifsnref property.
     *
     * @return possible object is
     * {@link SNREF }
     */
    public SNREF getINPARAMIFSNREF() {
        return inparamifsnref;
    }

    /**
     * Sets the value of the inparamifsnref property.
     *
     * @param value allowed object is
     *              {@link SNREF }
     */
    public void setINPARAMIFSNREF(SNREF value) {
        this.inparamifsnref = value;
    }

    /**
     * Gets the value of the inparamifsnpathref property.
     *
     * @return possible object is
     * {@link SNPATHREF }
     */
    public SNPATHREF getINPARAMIFSNPATHREF() {
        return inparamifsnpathref;
    }

    /**
     * Sets the value of the inparamifsnpathref property.
     *
     * @param value allowed object is
     *              {@link SNPATHREF }
     */
    public void setINPARAMIFSNPATHREF(SNPATHREF value) {
        this.inparamifsnpathref = value;
    }

    /**
     * Gets the value of the semantic property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSEMANTIC() {
        return semantic;
    }

    /**
     * Sets the value of the semantic property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSEMANTIC(String value) {
        this.semantic = value;
    }

}
