//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.28 at 09:58:19 AM CET 
//


package com.javahacks.odx.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for SNPATHREF complex type.
 * <p>
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * <p>
 * &lt;pre&gt;
 * &amp;lt;complexType name="SNPATHREF"&amp;gt;
 * &amp;lt;complexContent&amp;gt;
 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 * &amp;lt;attribute name="SHORT-NAME-PATH" use="required"&amp;gt;
 * &amp;lt;simpleType&amp;gt;
 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt;
 * &amp;lt;pattern value="[a-zA-Z0-9_]{1,128}(\.[a-zA-Z0-9_]{1,128})*"/&amp;gt;
 * &amp;lt;/restriction&amp;gt;
 * &amp;lt;/simpleType&amp;gt;
 * &amp;lt;/attribute&amp;gt;
 * &amp;lt;/restriction&amp;gt;
 * &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SNPATHREF")
public class SNPATHREF {

    @XmlAttribute(name = "SHORT-NAME-PATH", required = true)
    protected String shortnamepath;

    /**
     * Gets the value of the shortnamepath property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSHORTNAMEPATH() {
        return shortnamepath;
    }

    /**
     * Sets the value of the shortnamepath property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSHORTNAMEPATH(String value) {
        this.shortnamepath = value;
    }

}
