//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.28 at 09:58:19 AM CET 
//


package com.javahacks.odx.model;

import javax.xml.bind.annotation.*;


/**
 * &lt;p&gt;Java class for STATIC-FIELD complex type.
 * <p>
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * <p>
 * &lt;pre&gt;
 * &amp;lt;complexType name="STATIC-FIELD"&amp;gt;
 * &amp;lt;complexContent&amp;gt;
 * &amp;lt;extension base="{}FIELD"&amp;gt;
 * &amp;lt;sequence&amp;gt;
 * &amp;lt;element name="FIXED-NUMBER-OF-ITEMS" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/&amp;gt;
 * &amp;lt;element name="ITEM-BYTE-SIZE" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/&amp;gt;
 * &amp;lt;/sequence&amp;gt;
 * &amp;lt;/extension&amp;gt;
 * &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "STATIC-FIELD")
public class STATICFIELD
        extends FIELD {

    @XmlElement(name = "FIXED-NUMBER-OF-ITEMS")
    @XmlSchemaType(name = "unsignedInt")
    protected long fixednumberofitems;
    @XmlElement(name = "ITEM-BYTE-SIZE")
    @XmlSchemaType(name = "unsignedInt")
    protected long itembytesize;

    /**
     * Gets the value of the fixednumberofitems property.
     */
    public long getFIXEDNUMBEROFITEMS() {
        return fixednumberofitems;
    }

    /**
     * Sets the value of the fixednumberofitems property.
     */
    public void setFIXEDNUMBEROFITEMS(long value) {
        this.fixednumberofitems = value;
    }

    /**
     * Gets the value of the itembytesize property.
     */
    public long getITEMBYTESIZE() {
        return itembytesize;
    }

    /**
     * Sets the value of the itembytesize property.
     */
    public void setITEMBYTESIZE(long value) {
        this.itembytesize = value;
    }

}
