//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.28 at 09:58:19 AM CET 
//


package com.javahacks.odx.model;

import javax.xml.bind.annotation.*;


/**
 * &lt;p&gt;Java class for SYSTEM complex type.
 * <p>
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * <p>
 * &lt;pre&gt;
 * &amp;lt;complexType name="SYSTEM"&amp;gt;
 * &amp;lt;complexContent&amp;gt;
 * &amp;lt;extension base="{}POSITIONABLE-PARAM"&amp;gt;
 * &amp;lt;choice&amp;gt;
 * &amp;lt;element name="DOP-REF" type="{}ODXLINK"/&amp;gt;
 * &amp;lt;element name="DOP-SNREF" type="{}SNREF"/&amp;gt;
 * &amp;lt;/choice&amp;gt;
 * &amp;lt;attribute name="SYSPARAM" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&amp;gt;
 * &amp;lt;/extension&amp;gt;
 * &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SYSTEM")
public class SYSTEM
        extends POSITIONABLEPARAM {

    @XmlElement(name = "DOP-REF")
    protected ODXLINK dopref;
    @XmlElement(name = "DOP-SNREF")
    protected SNREF dopsnref;
    @XmlAttribute(name = "SYSPARAM", required = true)
    protected String sysparam;

    /**
     * Gets the value of the dopref property.
     *
     * @return possible object is
     * {@link ODXLINK }
     */
    public ODXLINK getDOPREF() {
        return dopref;
    }

    /**
     * Sets the value of the dopref property.
     *
     * @param value allowed object is
     *              {@link ODXLINK }
     */
    public void setDOPREF(ODXLINK value) {
        this.dopref = value;
    }

    /**
     * Gets the value of the dopsnref property.
     *
     * @return possible object is
     * {@link SNREF }
     */
    public SNREF getDOPSNREF() {
        return dopsnref;
    }

    /**
     * Sets the value of the dopsnref property.
     *
     * @param value allowed object is
     *              {@link SNREF }
     */
    public void setDOPSNREF(SNREF value) {
        this.dopsnref = value;
    }

    /**
     * Gets the value of the sysparam property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSYSPARAM() {
        return sysparam;
    }

    /**
     * Sets the value of the sysparam property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSYSPARAM(String value) {
        this.sysparam = value;
    }

}
