//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.28 at 09:58:19 AM CET 
//


package com.javahacks.odx.model;

import javax.xml.bind.annotation.*;


/**
 * &lt;p&gt;Java class for TABLE-ENTRY complex type.
 * <p>
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * <p>
 * &lt;pre&gt;
 * &amp;lt;complexType name="TABLE-ENTRY"&amp;gt;
 * &amp;lt;complexContent&amp;gt;
 * &amp;lt;extension base="{}POSITIONABLE-PARAM"&amp;gt;
 * &amp;lt;sequence&amp;gt;
 * &amp;lt;element name="TARGET" type="{}ROW-FRAGMENT"/&amp;gt;
 * &amp;lt;element name="TABLE-ROW-REF" type="{}ODXLINK"/&amp;gt;
 * &amp;lt;/sequence&amp;gt;
 * &amp;lt;/extension&amp;gt;
 * &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TABLE-ENTRY")
public class TABLEENTRY
        extends POSITIONABLEPARAM {

    @XmlElement(name = "TARGET", required = true)
    @XmlSchemaType(name = "string")
    protected ROWFRAGMENT target;
    @XmlElement(name = "TABLE-ROW-REF", required = true)
    protected ODXLINK tablerowref;

    /**
     * Gets the value of the target property.
     *
     * @return possible object is
     * {@link ROWFRAGMENT }
     */
    public ROWFRAGMENT getTARGET() {
        return target;
    }

    /**
     * Sets the value of the target property.
     *
     * @param value allowed object is
     *              {@link ROWFRAGMENT }
     */
    public void setTARGET(ROWFRAGMENT value) {
        this.target = value;
    }

    /**
     * Gets the value of the tablerowref property.
     *
     * @return possible object is
     * {@link ODXLINK }
     */
    public ODXLINK getTABLEROWREF() {
        return tablerowref;
    }

    /**
     * Sets the value of the tablerowref property.
     *
     * @param value allowed object is
     *              {@link ODXLINK }
     */
    public void setTABLEROWREF(ODXLINK value) {
        this.tablerowref = value;
    }

}
