//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.28 at 09:58:19 AM CET 
//


package com.javahacks.odx.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;


/**
 * &lt;p&gt;Java class for TABLE-KEY complex type.
 * <p>
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * <p>
 * &lt;pre&gt;
 * &amp;lt;complexType name="TABLE-KEY"&amp;gt;
 * &amp;lt;complexContent&amp;gt;
 * &amp;lt;extension base="{}POSITIONABLE-PARAM"&amp;gt;
 * &amp;lt;choice&amp;gt;
 * &amp;lt;group ref="{}ODXLINK-TO-TABLE"/&amp;gt;
 * &amp;lt;group ref="{}SNREF-TO-TABLE"/&amp;gt;
 * &amp;lt;element name="TABLE-ROW-REF" type="{}ODXLINK"/&amp;gt;
 * &amp;lt;/choice&amp;gt;
 * &amp;lt;attribute name="ID" type="{http://www.w3.org/2001/XMLSchema}ID" /&amp;gt;
 * &amp;lt;/extension&amp;gt;
 * &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TABLE-KEY")
public class TABLEKEY
        extends POSITIONABLEPARAM {

    @XmlElementRefs({
            @XmlElementRef(name = "TABLE-REF", type = JAXBElement.class),
            @XmlElementRef(name = "TABLE-ROW-SNREF", type = JAXBElement.class),
            @XmlElementRef(name = "TABLE-SNREF", type = JAXBElement.class),
            @XmlElementRef(name = "TABLE-ROW-REF", type = JAXBElement.class)
    })
    protected List<JAXBElement<?>> rest;
    @XmlAttribute(name = "ID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Gets the rest of the content model.
     * <p>
     * &lt;p&gt;
     * You are getting this "catch-all" property because of the following reason:
     * The field name "TABLEROWSNREF" is used by two different parts of a schema. See:
     * line 3747 of file:/D:/development/projects/odx-viewer/src/main/resources/odx.xsd
     * line 3735 of file:/D:/development/projects/odx-viewer/src/main/resources/odx.xsd
     * &lt;p&gt;
     * To get rid of this property, apply a property customization to one
     * of both of the following declarations to change their names:
     * Gets the value of the rest property.
     * <p>
     * &lt;p&gt;
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a &lt;CODE&gt;set&lt;/CODE&gt; method for the rest property.
     * <p>
     * &lt;p&gt;
     * For example, to add a new item, do as follows:
     * &lt;pre&gt;
     * getRest().add(newItem);
     * &lt;/pre&gt;
     * <p>
     * <p>
     * &lt;p&gt;
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link ODXLINK }{@code >}
     * {@link JAXBElement }{@code <}{@link SNREF }{@code >}
     * {@link JAXBElement }{@code <}{@link SNREF }{@code >}
     * {@link JAXBElement }{@code <}{@link ODXLINK }{@code >}
     */
    public List<JAXBElement<?>> getRest() {
        if (rest == null) {
            rest = new ArrayList<JAXBElement<?>>();
        }
        return this.rest;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setID(String value) {
        this.id = value;
    }

}
