//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.28 at 09:58:19 AM CET 
//


package com.javahacks.odx.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for UNIT-GROUP-CATEGORY.
 * <p>
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * &lt;pre&gt;
 * &amp;lt;simpleType name="UNIT-GROUP-CATEGORY"&amp;gt;
 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt;
 * &amp;lt;enumeration value="COUNTRY"/&amp;gt;
 * &amp;lt;enumeration value="EQUIV-UNITS"/&amp;gt;
 * &amp;lt;/restriction&amp;gt;
 * &amp;lt;/simpleType&amp;gt;
 * &lt;/pre&gt;
 */
@XmlType(name = "UNIT-GROUP-CATEGORY")
@XmlEnum
public enum UNITGROUPCATEGORY {

    COUNTRY("COUNTRY"),
    @XmlEnumValue("EQUIV-UNITS")
    EQUIV_UNITS("EQUIV-UNITS");
    private final String value;

    UNITGROUPCATEGORY(final String v) {
        value = v;
    }

    public static UNITGROUPCATEGORY fromValue(final String v) {
        for (final UNITGROUPCATEGORY c : UNITGROUPCATEGORY.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

    public String value() {
        return value;
    }

}
