//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.28 at 09:58:19 AM CET 
//


package com.javahacks.odx.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for USAGE.
 * <p>
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * &lt;pre&gt;
 * &amp;lt;simpleType name="USAGE"&amp;gt;
 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt;
 * &amp;lt;enumeration value="ECU-SOFTWARE"/&amp;gt;
 * &amp;lt;enumeration value="ECU-COMM"/&amp;gt;
 * &amp;lt;enumeration value="APPLICATION"/&amp;gt;
 * &amp;lt;enumeration value="TESTER"/&amp;gt;
 * &amp;lt;/restriction&amp;gt;
 * &amp;lt;/simpleType&amp;gt;
 * &lt;/pre&gt;
 */
@XmlType(name = "USAGE")
@XmlEnum
public enum USAGE {

    @XmlEnumValue("ECU-SOFTWARE")
    ECU_SOFTWARE("ECU-SOFTWARE"),
    @XmlEnumValue("ECU-COMM")
    ECU_COMM("ECU-COMM"),
    APPLICATION("APPLICATION"),
    TESTER("TESTER");
    private final String value;

    USAGE(String v) {
        value = v;
    }

    public static USAGE fromValue(String v) {
        for (USAGE c : USAGE.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

    public String value() {
        return value;
    }

}
