//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.28 at 09:58:19 AM CET 
//


package com.javahacks.odx.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for VALID-TYPE.
 * <p>
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * &lt;pre&gt;
 * &amp;lt;simpleType name="VALID-TYPE"&amp;gt;
 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt;
 * &amp;lt;enumeration value="VALID"/&amp;gt;
 * &amp;lt;enumeration value="NOT-VALID"/&amp;gt;
 * &amp;lt;enumeration value="NOT-DEFINED"/&amp;gt;
 * &amp;lt;enumeration value="NOT-AVAILABLE"/&amp;gt;
 * &amp;lt;/restriction&amp;gt;
 * &amp;lt;/simpleType&amp;gt;
 * &lt;/pre&gt;
 */
@XmlType(name = "VALID-TYPE")
@XmlEnum
public enum VALIDTYPE {

    VALID("VALID"),
    @XmlEnumValue("NOT-VALID")
    NOT_VALID("NOT-VALID"),
    @XmlEnumValue("NOT-DEFINED")
    NOT_DEFINED("NOT-DEFINED"),
    @XmlEnumValue("NOT-AVAILABLE")
    NOT_AVAILABLE("NOT-AVAILABLE");
    private final String value;

    VALIDTYPE(String v) {
        value = v;
    }

    public static VALIDTYPE fromValue(String v) {
        for (VALIDTYPE c : VALIDTYPE.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

    public String value() {
        return value;
    }

}
