//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.28 at 09:58:19 AM CET 
//


package com.javahacks.odx.model;

import org.eclipse.persistence.oxm.annotations.XmlPath;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * &lt;p&gt;Java class for WRITE-DIAG-COMM-CONNECTOR complex type.
 * <p>
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * <p>
 * &lt;pre&gt;
 * &amp;lt;complexType name="WRITE-DIAG-COMM-CONNECTOR"&amp;gt;
 * &amp;lt;complexContent&amp;gt;
 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 * &amp;lt;sequence&amp;gt;
 * &amp;lt;choice&amp;gt;
 * &amp;lt;element name="WRITE-DIAG-COMM-REF" type="{}ODXLINK"/&amp;gt;
 * &amp;lt;element name="WRITE-DIAG-COMM-SNREF" type="{}SNREF"/&amp;gt;
 * &amp;lt;/choice&amp;gt;
 * &amp;lt;element name="WRITE-PARAM-VALUES" type="{}WRITE-PARAM-VALUES" minOccurs="0"/&amp;gt;
 * &amp;lt;choice&amp;gt;
 * &amp;lt;element name="WRITE-DATA-SNREF" type="{}SNREF"/&amp;gt;
 * &amp;lt;element name="WRITE-DATA-SNPATHREF" type="{}SNPATHREF"/&amp;gt;
 * &amp;lt;/choice&amp;gt;
 * &amp;lt;/sequence&amp;gt;
 * &amp;lt;/restriction&amp;gt;
 * &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WRITE-DIAG-COMM-CONNECTOR")
public class WRITEDIAGCOMMCONNECTOR {

    @XmlElement(name = "WRITE-DIAG-COMM-REF")
    protected ODXLINK writediagcommref;
    @XmlElement(name = "WRITE-DIAG-COMM-SNREF")
    protected SNREF writediagcommsnref;
    @XmlElement(name = "WRITE-DATA-SNREF")
    protected SNREF writedatasnref;
    @XmlElement(name = "WRITE-DATA-SNPATHREF")
    protected SNPATHREF writedatasnpathref;

    @XmlPath("WRITE-PARAM-VALUES/WRITE-PARAM-VALUE")
    protected List<WRITEPARAMVALUE> writeparamvalues = new ArrayList<>();

    /**
     * Gets the value of the writediagcommref property.
     *
     * @return possible object is
     * {@link ODXLINK }
     */
    public ODXLINK getWRITEDIAGCOMMREF() {
        return writediagcommref;
    }

    /**
     * Sets the value of the writediagcommref property.
     *
     * @param value allowed object is
     *              {@link ODXLINK }
     */
    public void setWRITEDIAGCOMMREF(final ODXLINK value) {
        this.writediagcommref = value;
    }

    /**
     * Gets the value of the writediagcommsnref property.
     *
     * @return possible object is
     * {@link SNREF }
     */
    public SNREF getWRITEDIAGCOMMSNREF() {
        return writediagcommsnref;
    }

    /**
     * Sets the value of the writediagcommsnref property.
     *
     * @param value allowed object is
     *              {@link SNREF }
     */
    public void setWRITEDIAGCOMMSNREF(final SNREF value) {
        this.writediagcommsnref = value;
    }


    /**
     * Gets the value of the writedatasnref property.
     *
     * @return possible object is
     * {@link SNREF }
     */
    public SNREF getWRITEDATASNREF() {
        return writedatasnref;
    }

    /**
     * Sets the value of the writedatasnref property.
     *
     * @param value allowed object is
     *              {@link SNREF }
     */
    public void setWRITEDATASNREF(final SNREF value) {
        this.writedatasnref = value;
    }

    /**
     * Gets the value of the writedatasnpathref property.
     *
     * @return possible object is
     * {@link SNPATHREF }
     */
    public SNPATHREF getWRITEDATASNPATHREF() {
        return writedatasnpathref;
    }

    /**
     * Sets the value of the writedatasnpathref property.
     *
     * @param value allowed object is
     *              {@link SNPATHREF }
     */
    public void setWRITEDATASNPATHREF(final SNPATHREF value) {
        this.writedatasnpathref = value;
    }

    public List<WRITEPARAMVALUE> getWriteparamvalues() {
        return writeparamvalues;
    }
}
